### ISSUE TITLE
Add "source specific multicast" support to use with IP_ADD_SOURCE_MEMBERSHIP

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Mellanox/libvma#1]
```
Currently VMA only support IGMPv2 with IP_ADD_MEMBERSHIP.
```

Original issue reported on code.google.com by `rosenbau...@gmail.com` on 1 Oct 2013 at 2:20

**Comment by sbob84** [comment]
Hi! Any updates on this feature?

**Comment by rosenbaumalex** [comment]
Can you elaborate more about the specific use case you would like to get?

1) VMA to do the MC Source Filtering in software (or hardware if possible)?
2) VMA to supporting the setsockopt() API so the MC Source Filtering will work in the switches? 
3) IGMP v3 is required for this. Currently VMA is certified with IGMP v2 only. We expect this is very little code change and mainly testing effort

**Comment by sbob84** [comment]
Sure.

I’d like VMA to support IP_ADD_SOURCE_MEMBERSHIP setsockopt() so the system could respond to incoming JoinGroup messages and to produce NewSource messages.

The network I’m currently working in uses a source specific multicasting, so by now to connect and to stay connected to data streams I’m working with, I have to use timer based sends with the use of RAW sockets to emulate these v3 messages.

**Comment by sm1ly** [comment]
what about this issue?

**Comment by OphirMunk** [comment]
Hi,
The crash issue was fixed, see post on Oct-6. All other issues were addressed as well.
What specific issue are you asking about?

**Comment by sm1ly** [comment]
I'm asking about issue #1 
Add "source specific multicast" support to use with IP_ADD_SOURCE_MEMBERSHIP
any fixes or roadmaps ?

**Comment by rosenbaumalex** [comment]
depending on other tasks priority we might reach this task during 2016.

**Comment by omgtehlion** [comment]
any updates on this?

**Comment by EduardOGAN** [comment]
is the issure on working?

**Comment by sbob84** [comment]
Hi, still missing this feature.

**Comment by rosenbaumalex** [comment]
@sbob84 
Hi, with which commit did you check this?
This past Friday (Sep 2, 2016), we pushed https://github.com/Mellanox/libvma/commit/4a6348771d66fb75016c19137982885b5590fda0 (and bug fix  https://github.com/Mellanox/libvma/commit/9ffdc14ee9e7b94c01f709d05dec726e3c081629) for handling  IP_ADD_SOURCE_MEMBERSHIP support in VMA.

Our tests show this is working well now. 
If you can provide more feedback that would be great.

PR: I'm not sure why the "issue: 786030 revise RDTSC logic to consider CPU speeds taken from..." jump in here so many time. It is a mistake.

**Comment by rosenbaumalex** [comment]
We plan to close new tag which support the IP_ADD_SOURCE_MEMBERSHIP this week.

**Comment by sbob84** [comment]
Alex, I've just checked the recent commit and I can confirm that it works, that's a great news, thank you! I also noticed that vma_stats now says that its version is incompatible with current stats protocol.

**Comment by DanielLibenson** [comment]
Thank you for your feedback. This kind of  warning will appear if the VMA version is incompatible with the vma_stats version you are using. Try to run the vma_stats that comes as part of your latest VMA and not the one that is installed on your machine.

**Comment by rosenbaumalex** [comment]
if you used vma from local build folder: `./src/vma/.lib.libvma.so`
then you need to use: `./src/stats/vma_stats`

**Comment by sbob84** [comment]
Daniel, Alex, I found out what happened. I did 'make uninstall' inside the new versions's folder. But the previous version was installed into /usr/lib, so it's my mistake, sorry. Once again, thanks.
