### ISSUE TITLE
Libvma : 8.9.4  arp caching

### ISSUE THREAD

**Issue by gmangat-st** [Mellanox/libvma#1022]
## Issue type
- [x ] Bug report
- [ ] Feature request

## Configuration:
* Product version : 8.9.4
* OS : Fedora 29 , kernel 4.19.82-1300
* OFED : 4.7
* Hardware :   ConnectX-4 

libvma linked against  libnl3

offloading  does not work unless  gateway mac is in arp cache
LD_PRELOAD=libvma.so nc -v   <DEST_IP> <port>   --> fails/times out 

ip route get <DEST_IP> ,  and then ping gateway.  verified mac address in cache { arp -a |grep gateway }

LD_PRELOAD=libvma.so nc -v   <DEST_IP> <port>   --> success

**Comment by igor-ivanov** [comment]
@gmangat-st your details describe very old libvma anf OFED versions. I would recommend moving to something newest if possible.

**Comment by gmangat-st** [comment]
Hi @igor-ivanov 
Thanks for looking into it. 
We did try with  9.7.2  and see same problem

**Comment by gmangat-st** [comment]
am sorry,  misread regarding OFED version.

**Comment by gmangat-st** [comment]
openibd service was failing i.e not loading rdma_ucm 
issue is resolved
