### ISSUE TITLE
Unable to build libvma rpm follow the build instruction wiki

### ISSUE THREAD

**Issue by andl** [Mellanox/libvma#1053]
## Subject 
I'm trying to build libvma from source, while https://github.com/Mellanox/libvma/wiki/Build-Instruction is outdated.

## Issue type
- [X] Bug report
- [] Feature request

## Configuration:
* Product version libvma-9.8.40
* OS CentOS7.6 
* OFED 5.8-3.0.7.0
* Hardware all

## Actual behavior:
first, the `install.sh` script is deleted, so only manual build is possible. I can complete the build by run `./autogen.sh`, `./configure --with-ofed=/usr --prefix=/usr --libdir=/usr/lib64 --includedir=/usr/include --docdir=/usr/share/doc/libvma --sysconfdir=/etc ` and `./make`. But I can't find rpm build script at `./build/build_rpm.sh`.

I also did some search in code base, `./contrib/jenkins_tests/rpm.sh` seems realted to rpm build but I'm not sure if this is the offical way to build rpm.  

## Expected behavior:
able to follow the wiki and complete rpm build. 
## Steps to reproduce:
N/A

**Comment by igor-ivanov** [comment]
Hello @andl. to build source or binary rpm/deb packages you can use https://github.com/Mellanox/libvma/blob/master/contrib/build_pkg.sh. See help output.

**Comment by andl** [comment]
> Hello @andl. to build source or binary rpm/deb packages you can use https://github.com/Mellanox/libvma/blob/master/contrib/build_pkg.sh. See help output.

thanks, it's working.
