### ISSUE TITLE
Error in offloading vlan + bond interfaces

### ISSUE THREAD

**Issue by mellanoxer** [Mellanox/libvma#109]
VMA 8.0.4, OFED-3.2-2.0, latest firmware
There is link aggregation: eth0+eth1=>bond0, 802.3ad, fail_over_mac=0
There is 2 vlans over bonding: bond0.101 and bond0.102

While "Checking if can offload on interface 'bond0.102'" it was error  ndtm[0xfe9470]:203:map_net_devices() Failed in rdma_bind_addr (src=......) (errno=2 No such file or         directory)
But bond0.101 succesfully marked as offloaded interface and Mapped to ibv device 'mlx4_0'

After rebooting machine I've got reversed case, when bond0.102 was offloaded interface, but bond0.101 failed to offload with ndtm error "Failed in rdma_bind_addr "

I cant public full logs, so I've sent it to email.

**Comment by mellanoxer** [comment]
I've dig a little bit in the problem and found that rdma_bind_addr() return errno=2 in cases where more complex routing tables are exists in OS, so it confuses rdma. But i'm not totally sure about it, because routing table is interpreted correctly if we don't use libvma+rdma. So, temporary workaround is to simplify routing table as much as possible and try again libvma.

**Comment by mellanoxer** [comment]
I think this error is in responsibility of RDMA, but not libvma, so i suppose we can close this issue.

**Comment by mellanoxer** [comment]
I have to add some comments here. After rebooting machine I have the same error. It is horrible. I'm starting to regret of choosing Mellanox and think about to replace it with Solar...

**Comment by ErezF** [comment]
Can you please send whatever logs that you have to my email erezf@mellanox.com ? your routing table will be helpful too 
I'll try to quickly match my setup with yours, and if that doesn't yield results we can do a session.

**Comment by OphirMunk** [comment]
@mellanoxer We are not able to reproduce your case. We tried it by several engineers and a Field Application Engineer. 
Can you please answer ErezF request?
If you can suggest a Team Viewer session - we will assist.
