### ISSUE TITLE
 Unexpected behaviour of libvma

### ISSUE THREAD

**Issue by hello-users** [Mellanox/libvma#122]
Hello!

I have very strange situation with libvma. My C++ program is using TCP sockets and communicating with the server.
Almost every time two types of errors occur: "Resource temporarily unavailable" and "Resource busy".
But sometimes program works without any error and it works perfectly every time without offloading.

I tried many variants to determine the source of problem and experiment with different parameters.

First, when I tried launch it in debug logging mode it still works _with_ errors.
`LD_PRELOAD=libvma.so VMA_LOG_FILE=./logvma.log VMA_TRACELEVEL=debug ./program`
log file: [vma_debug_errors.txt](https://github.com/Mellanox/libvma/files/325388/vma_debug_errors.txt)
P.S. there is 4 ip addresses on offloaded interface in the log,  same situation for single ip address.

When I launch it in full logging mode, all errors _disappeared_.
`LD_PRELOAD=libvma.so VMA_LOG_FILE=./logvma.log VMA_TRACELEVEL=all ./program`

Then I tried to find minimal log level, there were no errors:
`LD_PRELOAD=libvma.so VMA_LOG_FILE=./logvma.log VMA_TRACELEVEL=debug VMA_LOG_DETAILS=3 ./program`
And there are still no errors in this mode

My hypothesis is that error disappears because of heavy log functions that could hide some bugs. In "nolog" cases error occurs because something is broken in libvma. I tried to experiment with `VMA_INTERNAL_THREAD_AFFINITY, VMA_RING_ALLOCATION_LOGIC, VMA_RING_MIGRATION_RATIO_RX, VMA_MEM_ALLOC_TYPE`  and it didn't give me any result.

Do you have any ideas why it happens?

OS: RHEL 7.2
Network adapter: ConnectX-3 SFP+ fw 2.36.5000 (also tried earlier firmwares)
libvma version: 7.0.14-0 (also tried earlier versions)
OFED version: 3.3-1.0.0.0-rhel7.2-x86_64  (also tried earlier versions)
Socket options is usual: `socket(AF_INET, SOCK_STREAM, 0);` (also tried different variations)

**Comment by hello-users** [comment]
Any ideas? Problem still exist. Please, let know if you have any hypothesis.

**Comment by OphirMunk** [comment]
@hello-users Please re-test with latest VMA version from GitHub and let know the status

**Comment by OphirMunk** [comment]
@hello-users 
1. what does dmesg show when an error occurs?
2. What is the strace of your run (without VMA) - in other words, what system calla are used? 
3. What is vma_stats printout when running with VMA?

**Comment by OphirMunk** [comment]
@hello-users how did you install OFED?
I recommend the following installation: 
```
mlnxofedinstall --vma --force --force-fw-update
```

**Comment by hello-users** [comment]
@OphirMunk hello! Thanks for advises.

1) I have updated firmware in your way:
` ./mlnxofedinstall --vma --force --force-fw-update --add-kernel-support`

I added `--add-kernel-support`, because `mlnxofedinstall` say to add this flag.

Kernel version is:
```
cat /proc/version
Linux version 3.10.0-327.18.2.el7.x86_64 (builder@kbuilder.dev.centos.org) (gcc version 4.8.3 20140911 (Red Hat 4.8.3-9) (GCC) ) #1 SMP Thu May 12 11:03:55 UTC 2016
```

2) I have installed lastest stable commit:
`https://github.com/Mellanox/libvma/commit/4e43c4cc687d41e4f2a80b2cf0b60ba0d983d24a`

So, looks like this with latest firmware and VMA:
```
LD_PRELOAD=libvma.so ls
VMA INFO: ---------------------------------------------------------------------------
VMA INFO: VMA_VERSION: 8.1.1-0 Development Snapshot built on Aug 13 2016 05:14:38
VMA INFO: Cmd Line: ls --color=auto
VMA INFO: Current Time: Mon Aug 15 01:30:23 2016
VMA INFO: Pid: 27445
VMA INFO: OFED Version: MLNX_OFED_LINUX-3.3-1.0.4.0:
VMA INFO: Architecture: x86_64
VMA INFO: Node: ***
VMA INFO: ---------------------------------------------------------------------------
VMA INFO: Log Level                      INFO                       [VMA_TRACELEVEL]
VMA INFO: ---------------------------------------------------------------------------

```

Btw, here is device:

```
ibdev2netdev -v
0000:04:00.0 mlx4_0 (MT4099 - MT1412X04648) CX312A - ConnectX-3 SFP+ fw 2.36.5000 port 1 (ACTIVE) ==> ens1 (Up)
0000:04:00.0 mlx4_0 (MT4099 - MT1412X04648) CX312A - ConnectX-3 SFP+ fw 2.36.5000 port 2 (ACTIVE) ==> ens1d1 (Up)
```

3) in case `LD_PRELOAD=libvma.so VMA_LOG_FILE=./logvma.log VMA_TRACELEVEL=debug VMA_LOG_DETAILS=3 ./program`
`vma_stats` shows offloaded traffic:

```
vmastat: stats for application: program with pid: 13377
 fd      ------------ total offloaded -------------   --------- total os ----------
                pkt   Kbyte   eagain   error  poll%     pkt   Kbyte  eagain   error
 27  Rx:         66       1 395109140       0  100.0       0       0       0       0
     Tx:         34       0         0       0              0       0       0       0
-------------------------------------------------------------------------------
 27  Rx:         67       1 397530485       0  100.0       0       0       0       0
     Tx:         35       0         0       0              0       0       0       0
-------------------------------------------------------------------------------
 27  Rx:         67       1 398766270       0  100.0       0       0       0       0
     Tx:         35       0         0       0              0       0       0       0
-------------------------------------------------------------------------------
 27  Rx:         67       1 401162903       0  100.0       0       0       0       0
     Tx:         35       0         0       0              0       0       0       0
-------------------------------------------------------------------------------
 27  Rx:         68       1 403588606       0  100.0       0       0       0       0
     Tx:         35       0         0       0              0       0       0       0
-------------------------------------------------------------------------------
```

in case `LD_PRELOAD=libvma.so ./program`  new sockets appears:
```
-------------------------------------------------------------------------------
 27  Rx:          5       0 22107054       0  100.0       0       0       0       0
     Tx:          4       0        0       0              0       0       0       0
 9   Rx:          0       0        0       0    0.0       0       0       0       0
     Tx:          0       0        0       0              0       0       0       0
 9   Rx:          3       0 12330143       0  100.0       0       0       0       0
     Tx:          2       0        0       0              0       0       0       0
 9   Rx:          0       0        0       0    0.0       0       0       0       0
     Tx:          0       0        0       0              0       0       0       0
 9   Rx:          5       0 24450236       0  100.0       0       0       0       0
     Tx:          3       0        0       0              0       0       0       0
 9   Rx:          0       0        0       0    0.0       0       0       0       0
     Tx:          0       0        0       0              0       0       0       0
 9   Rx:         10       0 36638276       0  100.0       0       0       0       0
     Tx:          5       0        0       0              0       0       0       0
 9   Rx:          0       0        0       0    0.0       0       0       0       0
     Tx:          0       0        0       0              0       0       0       0
 0   Rx:          0       0        0       0    0.0       0       0       0       0
     Tx:          0       0        0       0              0       0       0       0
-------------------------------------------------------------------------------
```

4) This lines occurs in `dmesg`, but it isn't related to problem:
```
[ 2076.518412] program[12354]: segfault at 0 ip 00007fb0b2b6b0aa sp 00007fb0af091ae0 error 6 in libvma.so.8.1.1[7fb0b2ac4000+142000]
[ 2121.432449] program[12433]: segfault at 0 ip 00007f3f8eebb0aa sp 00007f3f8b3e1ae0 error 6 in libvma.so.8.1.1[7f3f8ee14000+142000]
[ 2276.838915] program[12569]: segfault at 0 ip 00007fd146f140aa sp 00007fd14343aae0 error 6 in libvma.so.8.1.1[7fd146e6d000+142000]
[ 2493.141863] program[12635]: segfault at 0 ip 00007f3d743a70aa sp 00007f3d708cdae0 error 6 in libvma.so.8.1.1[7f3d74300000+142000]
[ 2737.192082] program[12709]: segfault at 0 ip 00007f8a4b4e80aa sp 00007f8a47a0eae0 error 6 in libvma.so.8.1.1[7f8a4b441000+142000]
[ 2765.739548] program[12754]: segfault at 0 ip 00007f60577080aa sp 00007f6053c2eae0 error 6 in libvma.so.8.1.1[7f6057661000+142000]
[ 2867.428526] program[12901]: segfault at 0 ip 00007fa8e6d110aa sp 00007fa8e3237ae0 error 6 in libvma.so.8.1.1[7fa8e6c6a000+142000]
[ 2962.082666] program[12946]: segfault at 0 ip 00007f563ea740aa sp 00007f563af9aae0 error 6 in libvma.so.8.1.1[7f563e9cd000+142000]
[ 4334.459781] program[20260]: segfault at 10 ip 00007f3ecbd05bf0 sp 00007f3ec81dabc0 error 4 in libvma.so.8.1.1[7f3ecbc0d000+140000]
```
When error occurs `dmesg` is empty.

5) `strace` log of problem is attached: [strace.txt](https://github.com/Mellanox/libvma/files/418747/strace.txt)

**Comment by hello-users** [comment]
Seems pretty similar to [Unexpected behavior of libvma](https://github.com/Mellanox/libvma/issues/188)

@OphirMunk, if you need more info/logs about this issue, that won't be a problem.

**Comment by igor-ivanov** [comment]
Hi @hello-users, thank you for contribution to the project. Could you please check https://github.com/Mellanox/libvma/releases/tag/8.9.2 that should include a fix for the issue you described.
