### ISSUE TITLE
Unexpected behavior of libvma ("Device or resource busy" / EBUSY)

### ISSUE THREAD

**Issue by siddharthaagrawal** [Mellanox/libvma#188]
Hi all,
Would love to get some help on this: We have an application that opens TCP and UDP Multicast sockets and we use VMA to accelerate it. Everything works well on RHEL 6.5 with VMA 6.4 (ConnectX 3). 

On upgrading to RHEL 6.7 and OFED 3.3 with VMA 8.0.4 (or indeed, with VMA 8.1.3 Development snapshot), we have begun to consistently see an issue where TCP recv() returns with error EBUSY ("Device or resource busy"). This is a non-blocked TCP socket and we expect EAGAIN or EWOULDBLOCK, but EBUSY is unexpected. (The application busy-spins on this socket).

Further, the application works properly _without_ accelerating with VMA also.

VMA log at debug trace level attached: 
[vma_recv_resource_busy_error_default_non_blocked_tcp.txt](https://github.com/Mellanox/libvma/files/432010/vma_recv_resource_busy_error_default_non_blocked_tcp.txt)

(This may be related to issue #122 (Unexpected behaviour of libvma) but still opening a different issue as I feel it may be related to non-blocked behavior.)

OS: RHEL 6.7
Network adapter: Mellanox ConnectX-3 10 Gbps SFP+ 2 port NI, fw 2.36.5000
libvma version: 8.0.4 (also tried 8.1.3)
OFED version: MLNX_OFED_LINUX-3.3-1.0.4.0 (OFED-3.3-1.0.4)
Socket options is usual: `socket(PF_INET, SOCK_STREAM, IPPROTO_TCP)`, `flags |= O_NONBLOCK; fcntl(socket_, F_GETFL, 0)`

**Comment by siddharthaagrawal** [comment]
It may seem too soon after I posted, but looks like introducing a 1 ms sleep after TCP connect() or before the first TCP recv() or send() allows the application to work normally. It looks like the socket connect() is taking some time, and it would be nice to understand if this is a regression? Also, as a workaround, we would prefer to get an error code such as EINPROGRESS or any other suitable error code rather than sleep. I will keep the thread posted in case I have a deterministic way of judging if the socket connect is completed.

**Comment by hello-users** [comment]
Yep, seems similar to my ticket [Unexpected behaviour of libvma](https://github.com/Mellanox/libvma/issues/122).

**Comment by hello-users** [comment]
@siddharthaagrawal do you need to use flag `--add-kernel-support` while installing drivers?

**Comment by siddharthaagrawal** [comment]
@hello-users No, that has not been necessary for CentOS/RHEL 6.x.

**Comment by siddharthaagrawal** [comment]
Bump!

**Comment by liranoz12** [comment]
Hi @siddharthaagrawal,

Can you please reproduce the issue using VMA_LOG_DETAILS=3 and VMA_TRACELEVEL=FINE and upload the output?
If it is possible, please provide us an application that reproduces the issue.

Liran.

**Comment by igor-ivanov** [comment]
Hi @siddharthaagrawal, thank you for contribution to the project. Could you please check https://github.com/Mellanox/libvma/releases/tag/8.9.2 that should include a fix for the issue you described.
