### ISSUE TITLE
Support for 802.3ad bonding mode

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Mellanox/libvma#20]
```
What need is this feature going to satisfy?
1. support for 802.3ad bonding mode

What is the expected output? What do you have currently? Any workaround?
Currently active-backup mode only is availaible with fail_over_mac=1

Please use labels and text to provide additional information.


```

Original issue reported on code.google.com by `galush...@gmail.com` on 13 Aug 2014 at 2:31

**Comment by rosenbaumalex** [comment]
We recently added active-backup mode with fail_over_mac=0 on Ethernet link layers.
This is in addition to the active-backup mode with fail_over_mac=1 which is available on IB and Ethernet.
This is available in VMA 7.0.4 - https://github.com/Mellanox/libvma/releases/tag/7.0.4

We've started working on adding Active/Active LAG support (mode=4). We're targeting Oct~Nov release of this feature.

**Comment by sm1ly** [comment]
what about vlans on bonding interfaces?
centos 7.1 both styles ifcfg-vlan77/bond0.77 doest work.
 VMA ERROR  : utils:238:priv_read_file() ERROR while opening file /sys/class/net/bond0/device/resource (errno 2 No such file or directory)
 VMA PANIC  : ring[0x21c02b0]:170:create_resources() ibv_create_comp_channel for tx failed. m_p_tx_comp_event_channel = (nil) (errno=9 Bad file descriptor)

I tried 7.0.6 and 7.0.7 versions

**Comment by rosenbaumalex** [comment]
I added a comment in the dedicated bug you opened (https://github.com/Mellanox/libvma/issues/31).
The fix for VLAN over bond issue will be pushed out in few days.

**Comment by rosenbaumalex** [comment]
All pushed in VMA 7.0.9.
https://github.com/Mellanox/libvma/releases/tag/7.0.9
