### ISSUE TITLE
Broken cubic implementation

### ISSUE THREAD

**Issue by stablebits** [Mellanox/libvma#25]
Hi,

I'm wondering whether this implementation of cubic has been used extensively? There seems to be an obvious problem in this code.

In cubic_record_rtt(), t_srtt_ticks is supposed to be a "smoothed round-trip time" but you use 'pcb->rttest', which is a timestamp taken upon sending a TCP segment (in tcp_out.c) to be used later (upon getting a corresponding ACK) to measure RTT.

With the current code, what will happen is that as tcp_ticks is growing over time, so the values of pcb->rttest are, and so cubic_data->mean_rtt_ticks becomes bigger and bigger, resulting in setting very big cwnd values (but it will outperform Linux ;-)).

I guess what should be used is something like this:

```
diff --git a/src/vma/lwip/cc_cubic.c b/src/vma/lwip/cc_cubic.c
index 4c78b7c..85e3a57 100644
--- a/src/vma/lwip/cc_cubic.c
+++ b/src/vma/lwip/cc_cubic.c
@@ -328,7 +328,7 @@ cubic_record_rtt(struct tcp_pcb *pcb)
 	/* Ignore srtt until a min number of samples have been taken. */
 	if (pcb->t_rttupdated >= CUBIC_MIN_RTT_SAMPLES) {
 
-		t_srtt_ticks = pcb->rttest;
+		t_srtt_ticks = pcb->sa >> 3;
 
 		/*
 		 * Record the current SRTT as our minrtt if it's the smallest
```

--Dmitry

**Comment by orkmellanox** [comment]
Thank you!
You are correct.
This code was not used much as it is not the default for libvma.
We will push your patch and update you.

**Comment by orkmellanox** [comment]
fixed, please see:
https://github.com/Mellanox/libvma/commit/3fe90c20299c93f02918e52a0a6a691cf31b2d4e

**Comment by stablebits** [comment]
Thanks!
