### ISSUE TITLE
VMA not sending via Ethernet on RH7,1

### ISSUE THREAD

**Issue by clameter** [Mellanox/libvma#28]
We run a test program that works fine with the kernel stack

 VMA INFO   : ---------------------------------------------------------------------------
 VMA INFO   : VMA_VERSION: 7.0.4-0 Release built on 2015-07-09-03:08:51
 VMA INFO   : Cmd Line: strace -o log ./OrderEntry T_JT009A1 azsxdc1234 7.40.28.11 21024 1
 VMA INFO   : OFED Version: ▒▒▒▒ VMA INFO   : Log Level                      3                          [VMA_TRACELEVEL]
 VMA INFO   : CQ Interrupts Moderation       Disabled                   [VMA_CQ_MODERATION_ENABLE]
 VMA INFO   : CQ Adaptive Moderation         Disabled                   [VMA_CQ_AIM_INTERVAL_MSEC]
 VMA INFO   : Mem Allocate type              1 (Contig Pages)           [VMA_MEM_ALLOC_TYPE]
 VMA INFO   : ---------------------------------------------------------------------------
 VMA INFO   : ---------------------------------------------------------------------------
 VMA INFO   : VMA_VERSION: 7.0.4-0 Release built on 2015-07-09-03:08:51
 VMA INFO   : Cmd Line: ./OrderEntry T_JT009A1 azsxdc1234 7.40.28.11 21024 1
 VMA INFO   : OFED Version: P▒▒▒ VMA INFO   : Log Level                      3                          [VMA_TRACELEVEL]
 VMA INFO   : CQ Interrupts Moderation       Disabled                   [VMA_CQ_MODERATION_ENABLE]
 VMA INFO   : CQ Adaptive Moderation         Disabled                   [VMA_CQ_AIM_INTERVAL_MSEC]
 VMA INFO   : Mem Allocate type              1 (Contig Pages)           [VMA_MEM_ALLOC_TYPE]
 VMA INFO   : ---------------------------------------------------------------------------

strace output

select(23, [], [], NULL, {0, 0})        = 0 (Timeout)
select(23, [], [], NULL, {0, 0})        = 0 (Timeout)
select(23, [], [], NULL, {0, 0})        = 0 (Timeout)
select(23, [], [], NULL, {0, 0})        = 0 (Timeout)
select(23, [], [], NULL, {0, 0})        = 0 (Timeout)
select(23, [], [], NULL, {0, 0})        = 0 (Timeout)
select(23, [], [], NULL, {0, 0})        = 0 (Timeout)
select(23, [], [], NULL, {0, 0})        = 0 (Timeout)
select(23, [], [], NULL, {0, 0})        = 0 (Timeout)
select(23, [14], [], NULL, {14, 899448}) = 1 (in [14], left {14, 899446})
epoll_wait(14, {{EPOLLIN, {u32=0, u64=0}}}, 16, 0) = 1
epoll_ctl(14, EPOLL_CTL_DEL, 15, NULL)  = 0
select(23, [14], [], NULL, {14, 899400}) = 0 (Timeout)
fcntl(22, F_GETFL)                      = 0x802 (flags O_RDWR|O_NONBLOCK)
fcntl(22, F_SETFL, O_RDWR|O_NONBLOCK)   = 0
times({tms_utime=6, tms_stime=26, tms_cutime=0, tms_cstime=0}) = 437715486
write(30, "0", 1)                       = 1
epoll_ctl(7, EPOLL_CTL_ADD, 5, {EPOLLIN, {u32=5, u64=7953746620024094725}}) = 0
close(22)                               = 0
futex(0x7ffff652a190, FUTEX_WAKE_PRIVATE, 2147483647) = 0
write(2, "terminate called after throwing "..., 48) = 48
write(2, "std::runtime_error", 18)      = 18

**Comment by rosenbaumalex** [comment]
Current VMA requires MLNX_OFED for proper operation. 
We're working on making all the necessary updates upstream to close the gap on the few missing features to fully support VMA. We're targeting RHEL 7.2 to achieve this goal.

Specifically we're working on pushing the user space send (and receive) check sum flag which will enable VMA to send Ethernet frame and the HW to add the CSUM on the egress path so the frame on the wire will be a compatible Ethernet frame.

**Comment by rosenbaumalex** [comment]
We'll update the ticket with more info once we reach the first upstream supported VMA distro (which does not require MLNX_OFED installed to work).

**Comment by clameter** [comment]
We are applying the patches at http://www.spinics.net/lists/linux-rdma/msg26233.html and http://www.spinics.net/lists/linux-rdma/msg26233.html to the RH7.1 libraries to get checksum support.

Is there a way to enable ethernet support after applying these patches? I am a bit skeptical about this feature making RH7.2 by the way given the recent interactions on the rdma mailing list.

**Comment by clameter** [comment]
DId not mean to close the issue.

**Comment by clameter** [comment]
It seems that we can successfully run the VMA with Ethernet support on some hosts and not on others. Is there any way to figure out what goes wrong? What other features are still missing?

**Comment by rosenbaumalex** [comment]
Is this still relevant issue?

Formally VMA does not support install on upstream IB stack yet.

Please provide more details so we can reproduce this with a MLNX_OFED release and include NIC type and FW version.
We don't see this issue in our regression tests on MLNX_OFED GA

**Comment by clameter** [comment]
This was fixed in release 7.0.5. The ethernet port were sometimes not set
up the right way and it would send from the wrong port.
