### ISSUE TITLE
VMA panic with iperf and Ethernet

### ISSUE THREAD

**Issue by clameter** [Mellanox/libvma#29]
Running iperf between two hosts via Ethernet:

VMA PANIC  : qpm[0x643be0]:556:prepare_ibv_qp() failed to modify QP from ERR to INIT state (ret = -3)

**Comment by rosenbaumalex** [comment]
Is this still relevant issue?

I'm guessing this is on an upstream IB stack. 
Formally VMA does not support this install yet.

please provide more details so we can reproduce this, like:
MLNX_OFED release?
NIC type and FW version?

we don't see this issue in our regression tests on MLNX_OFED GA

**Comment by clameter** [comment]
Well yes this was on Redhat 7.1. Have not seen it with 7.0.5
