### ISSUE TITLE
libvma crushes on vlan (on bond) interfaces

### ISSUE THREAD

**Issue by sm1ly** [Mellanox/libvma#31]
i got mlnx0+mlnx1=bond0 active-backup
and I got bond0.77 vlan interface.
centos 7.1

error:

 VMA ERROR  : utils:238:priv_read_file() ERROR while opening file /sys/class/net/vlan77/device/resource (errno 2 No such file or directory)
 VMA PANIC  : ring[0x14229e0]:199:create_resources() ibv_create_comp_channel for rx failed. p_rx_comp_event_channel = (nil) (errno=9 Bad file descriptor)

here is cannot be this file, cause interface is virtual, so why it try it to find?

**Comment by rosenbaumalex** [comment]
thanks for this report. 
we reproduced is easily and will publish a fix soon.

**Comment by rosenbaumalex** [comment]
Such a test case will be added to our regression for all bonding types VMA supports

**Comment by sm1ly** [comment]
thx a lot!!

**Comment by sm1ly** [comment]
we want this fix very very much!!!!

**Comment by sm1ly** [comment]
any actions?
"I added a comment in the dedicated bug you opened (#31).
The fix for VLAN over bond issue will be pushed out in few days."

**Comment by orkmellanox** [comment]
Hi,
I pushed the fix for this issue, the main change is in here:
https://github.com/Mellanox/libvma/commit/432723c0ca2b5e48060bf3b66b54bbf5e1bf15c5
but please pull latest head, as there are more related changes.

please note that:
1. it is not fully tested yet, we will complete testing in the next few days
2. vma does not offload vlan over bond if the bond is configured with fail_over_mac=1

**Comment by sm1ly** [comment]
so if I configure like mlnx0.100+mlnx1.100=bond0 - bodn0 will be offloaded?
and if I got mlnx0+mlnx1=bond0=bond0.100 it will not be offloaded?
so libvma works only with fail_over_mac=1, but if I use bond0.VLANTAG it doesnt work?
so u dont fix it?

**Comment by orkmellanox** [comment]
libvma works now with fail_over_mac=0 as well.
you may configure mlnx0+mlnx1=bond0=bond0.100 and it will be offloaded

**Comment by sm1ly** [comment]
oh, great, thx a lot!!
21 сент. 2015 г. 16:55 пользователь "orkmellanox" <notifications@github.com>
написал:

**Comment by NirNitzani** [comment]
Issue is closed
