### ISSUE TITLE
RHEL7.3 in box libvma does not appear to work across RoCE

### ISSUE THREAD

**Issue by rcroucher** [Mellanox/libvma#318]
We're testing the in box,  i.e. supplied by Redhat version of libvma included with  RHEL 7.3.

Does not work across RoCE.  Unable to test InfiniBand
Similar warnings given, then fails to make a connection.

VMA WARNING: ib_ctx_collection82:map_ib_devices() Failure in rdma_get_devices() (error=19 No such device)
VMA WARNING: ib_ctx_collection83:map_ib_devices() Please check OFED installation

Testing with netperf which works fine without libvma so there are no network/firewall issues.

Installing MLNX_OFED is not an option since it will taint the kernel and invalidate our Redhat support. The whole point of the inbox VMA drivers was meant to be so we avoid this tainting.

I thought one of the goals with RH7.3 was that it 'just worked' out of the box. Seems not, not with a just a 'yum install libvma' anyway.

**Comment by NirNitzani** [comment]
Hi Rcroucher ,

InfiniBand and RoCE are supported within RHEL 7.3 inbox for both mlx4 and mlx5 drivers.
You will need to install the InfiniBand user space packages (libibverbs, librdmacm, etc) to used them.
To install the InfiniBand packages within RHEL 7.3 run “yum install –y @infiniband”. 

One note - InfiniBand and VMA is currently supported only with ConnectX-3 NIC (currently)

I hope it answers your question.
