### ISSUE TITLE
VMA crashes when TCP connection is closed by peer

### ISSUE THREAD

**Issue by nijinboc** [Mellanox/libvma#32]
I have experienced a crash when TCP connections are terminated by peer (a Windows box).
Whenever, client (a Window box) closes a TCP connection, the server (running with socket offload) generates the following vma errors and crashes after few mins:

VMA ERROR  : vma_list_t.push_front() - buff is already a member in a list.

I am using:
firmware version 2.34.5000
MLNX_OFED version 3.0-2.0.1
VMA version 7.0.4

Besides, seems when in the socket offload mode, the TCP call accept() will not return even after shutdown() and closesocket() the server socket.

Jni

**Comment by orkmellanox** [comment]
Hi,
Thank you for this report.
We are looking for the source of these issues.

Can you try to pull latest libvma code, compile, and check it the issue still exist?
If so, can you paste here the crash backtrace and all libvma prints (including libvma header print)?

Thanks!

**Comment by nijinboc** [comment]
Thanks for the reply, I will try.

**Comment by nijinboc** [comment]
HI, wondering if anyone can help.
I am trying to build the latest code, but during configuration, it keeps giving me error:

./configure: line 17117: syntax error near unexpected token `LIBNL3,libnl-route-3.0,'
./configure: line 17117: `PKG_CHECK_MODULES(LIBNL3,libnl-route-3.0, have_libnl=yes'

I did installed libnl3.

Thanks

**Comment by orkmellanox** [comment]
Hi, try to install the development packages of libnl, e.g. libnl-3.0-devel ...
________________________________

**Comment by nijinboc** [comment]
Hi, Thanks for the reply,
But I did installed libnl-3.2.25 and I saws the libs generated in /usr/lib

**Comment by nijinboc** [comment]
And from the error messages, seems there is a syntax error in configure.ac

**Comment by nijinboc** [comment]
Hi, wondering if anyone has the same problem.
keep getting the error

./configure: line 17117: syntax error near unexpected token LIBNL3,libnl-route-3.0,'
./configure: line 17117:PKG_CHECK_MODULES(LIBNL3,libnl-route-3.0, have_libnl=yes'

and I do installed libnl3-devel-5.3.25-2.1.2.x86_64.rpm

**Comment by orkmellanox** [comment]
Hi,
Can you send us your system information?
OS flavor, version, etc..
Also the versions of:
pkg-config --version
automake --version
autoconf --version

I think I know what the issue is, but I don't have a reproduction, so could not test the fix.
Can you try to apply the attached patch and check?
If it fixes the issue i'll apply it.
[fix_configure_pkg_check_moduels.patch.txt](https://github.com/Mellanox/libvma/files/8231/fix_configure_pkg_check_moduels.patch.txt)

Thanks!

**Comment by nijinboc** [comment]
HI,
Actually I figured out yesterday.
It is because the pkg-config version is low (0.23) and kind of unable to recognize the syntax.
After I upgrade it to 0.29, then it's fine.
Also I need to specify the directory of libnl-route-3.0.pc for pkg-config in order to go through that module check.

Thanks.

**Comment by nijinboc** [comment]
HI,
I tested my build.
It works very well, all the issues I mentioned are gone.
Thank you so much for the help.
Waiting for the official release.

**Comment by nijinboc** [comment]
One question that puzzled me.
When use VMA, seems CPU usage sky soared, often more than 600% (I have around 12 TCP connections and I use top to monitor the CPU usage).
When running the same application without VMA, the CPU usage never more than 10%

Thanks.

**Comment by orkmellanox** [comment]
By default, VMA spend a lot of CPU time doing poliing (poll the NIC for new packets coming), to acheive best latency performance .
You probably have multiple threads doing networking, and in each of them VMA is doing polling, hence 600% CPU usage..
You can control polling using the VMA_RX_POLL and VMA_SELECT_POLL environment parameters (see README or wiki for more details).
You can save CPU cycles by doing less polling, but latency might be less good.

**Comment by nijinboc** [comment]
HI, Thanks for the replay.
I have already tried to Set the two parameters to 1, here are my parameter valus:

 VMA_BF=0
VMA_BUFFER_BATCHING_MODE=0
VMA_SELECT_POLL=1
VMA_RX_POLL_YIELD=1
VMA_RX_POLL=0
VMA_PROGRESS_ENGINE_INTERVAL_disable=0
VMA_CQ_MODERATION_ENABLE=0
VMA_CQ_AIM_INTERVAL_MSEC=0
VMA_THREAD_MODE=3

But seems still having the CPU peaking issues.
I have 6 cores and when using VMA, the CPU usage often reaches 599%, that means all cores are peaked (I did not restrict VMA threads to certain cores).

Jingbo bo

**Comment by nijinboc** [comment]
HI,
Also, sometimes, when clients quickly drop and re-establish TCP connections, the server (using VMA) will fail to response and just hang there. I have to killall -9 to terminate.
This happens more often when server is actively sending or receiving.
It's kind like there are some dead locking situations in VMA.

**Comment by orkmellanox** [comment]
can you give us the stack backtrace of the server when it hangs?
run `gstack <server pid>` multiple times and paste here or send us a file with info

**Comment by nijinboc** [comment]
Hi,

I tried several times and give my server fare amount of load, then got it hang there.
I attached two call stack dump files: stack_1.txt and stack_2.txt:

stack_1.txt is dumped at the moment that my server becomes not responsible for any client TCP connection request.
stack_2.txt is dumped at the moment that I try to shutdown the server and the server just hang there (this is because the main thread waiting for all client connection threads to return properly, but some of them fail to do so, just stuck there).

Thanks.

For some reason, I cannot attach my files, I just paste them here:

stack_1.txt:

Thread 10 (Thread 0x7f7c057a0700 (LWP 17674)):
#0  0x00000037e980be6c in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
#1  0x0000000000411385 in SyncLoggerTemp<SyncLoggerItemTemp<256u, 4096u, 1024u> >::Write(bool, unsigned int) ()
#2  0x00000000004113c2 in SyncLoggerTemp<SyncLoggerItemTemp<256u, 4096u, 1024u> >::LogProcessCallBack(void*) ()
#3  0x000000000040cc44 in System::Thread::Routine(void*) ()
#4  0x00000037e9807f05 in start_thread () from /lib64/libpthread.so.0
#5  0x00000037e94d953d in clone () from /lib64/libc.so.6
Thread 9 (Thread 0x7f7c04d74700 (LWP 17675)):
#0  0x00000037e94d9c13 in epoll_wait () from /lib64/libc.so.6
#1  0x00007f7c0a17ac51 in event_handler_manager::thread_loop() () from /usr/lib64/libvma.so
#2  0x00007f7c0a17b416 in event_handler_thread(void*) () from /usr/lib64/libvma.so
#3  0x00000037e9807f05 in start_thread () from /lib64/libpthread.so.0
#4  0x00000037e94d953d in clone () from /lib64/libc.so.6
Thread 8 (Thread 0x7f7c0112e700 (LWP 17680)):
#0  0x00000037e980be6c in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
#1  0x00000000004231de in SyncUDPSender::Process() ()
#2  0x0000000000423d79 in SyncUDPSender::ThreadCallBack(void*) ()
#3  0x000000000040cc44 in System::Thread::Routine(void*) ()
#4  0x00000037e9807f05 in start_thread () from /lib64/libpthread.so.0
#5  0x00000037e94d953d in clone () from /lib64/libc.so.6
Thread 7 (Thread 0x7f7bfbfff700 (LWP 17681)):
#0  0x00000037e980be6c in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
#1  0x0000000000417ec5 in FIXCompress::UDPIn<FixForwarder::Controller>::Process() ()
#2  0x0000000000417f69 in FIXCompress::UDPIn<FixForwarder::Controller>::ThreadCallBack(void*) ()
#3  0x000000000040cc44 in System::Thread::Routine(void*) ()
#4  0x00000037e9807f05 in start_thread () from /lib64/libpthread.so.0
#5  0x00000037e94d953d in clone () from /lib64/libc.so.6
Thread 6 (Thread 0x7f7bfb5fe700 (LWP 17682)):
#0  0x00000037e980be6c in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
#1  0x000000000040e2cf in FixForwarder::Client::Terminate() ()
#2  0x000000000040ece8 in FixForwarder::Client::Startup(int) ()
#3  0x0000000000415818 in FixForwarder::Controller::StartClient() ()
#4  0x00000000004158ef in FixForwarder::Controller::ServerProcess() ()
#5  0x0000000000417aa9 in FixForwarder::Controller::ServerCallBack(void*) ()
#6  0x000000000040cc44 in System::Thread::Routine(void*) ()
#7  0x00000037e9807f05 in start_thread () from /lib64/libpthread.so.0
#8  0x00000037e94d953d in clone () from /lib64/libc.so.6
Thread 5 (Thread 0x7f7bfabfd700 (LWP 17683)):
#0  0x00000037e94d9c13 in epoll_wait () from /lib64/libc.so.6
#1  0x00007f7c0a1c7e99 in sockinfo_tcp::rx_wait_helper(int&, bool) () from /usr/lib64/libvma.so
#2  0x00007f7c0a1c95da in sockinfo_tcp::accept_helper(sockaddr*, unsigned int*, int) () from /usr/lib64/libvma.so
#3  0x00000000004241a0 in TCPSocket::Accept() ()
#4  0x0000000000421e87 in RemoteConsole::TCPProcess() ()
#5  0x0000000000422a29 in RemoteConsole::StartTCPServer(void*) ()
#6  0x000000000040cc44 in System::Thread::Routine(void*) ()
#7  0x00000037e9807f05 in start_thread () from /lib64/libpthread.so.0
#8  0x00000037e94d953d in clone () from /lib64/libc.so.6
Thread 4 (Thread 0x7f7bfa1fc700 (LWP 17684)):
#0  0x00000037e980c1eb in pthread_cond_timedwait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
#1  0x000000000040b81c in CheckTime(void*) ()
#2  0x000000000040cc44 in System::Thread::Routine(void*) ()
#3  0x00000037e9807f05 in start_thread () from /lib64/libpthread.so.0
#4  0x00000037e94d953d in clone () from /lib64/libc.so.6
Thread 3 (Thread 0x7f7b8f12c700 (LWP 24605)):
#0  0x00000037e980be6c in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
#1  0x000000000040fae3 in FixForwarder::Client::InboundProcess() ()
#2  0x0000000000412699 in FixForwarder::Client::InboundCallBack(void*) ()
#3  0x000000000040cc44 in System::Thread::Routine(void*) ()
#4  0x00000037e9807f05 in start_thread () from /lib64/libpthread.so.0
#5  0x00000037e94d953d in clone () from /lib64/libc.so.6
Thread 2 (Thread 0x7f7b8e72a700 (LWP 24606)):
#0  0x00000037e980be6c in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
#1  0x0000000000411385 in SyncLoggerTemp<SyncLoggerItemTemp<256u, 4096u, 1024u> >::Write(bool, unsigned int) ()
#2  0x00000000004113c2 in SyncLoggerTemp<SyncLoggerItemTemp<256u, 4096u, 1024u> >::LogProcessCallBack(void*) ()
#3  0x000000000040cc44 in System::Thread::Routine(void*) ()
#4  0x00000037e9807f05 in start_thread () from /lib64/libpthread.so.0
#5  0x00000037e94d953d in clone () from /lib64/libc.so.6
Thread 1 (Thread 0x7f7c09c74740 (LWP 17652)):
#0  0x00000037e94d2c33 in select () from /lib64/libc.so.6
#1  0x00007f7c0a186ab3 in select_call::wait_os(bool) () from /usr/lib64/libvma.so
#2  0x00007f7c0a18457a in io_mux_call::call() () from /usr/lib64/libvma.so
#3  0x00007f7c0a1da1fa in select_helper(int, fd_set*, fd_set*, fd_set*, timeval*, __sigset_t const*) () from /usr/lib64/libvma.so
#4  0x0000000000421bb1 in RemoteConsole::ReadLine(char*, int) ()
#5  0x0000000000418298 in CmdConsole::GetCommands() ()
#6  0x000000000040b523 in StartCommandConsole() ()
#7  0x000000000040c334 in main ()

stack_2.txt

Thread 7 (Thread 0x7f7c057a0700 (LWP 17674)):
#0  0x00000037e980be6c in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
#1  0x0000000000411385 in SyncLoggerTemp<SyncLoggerItemTemp<256u, 4096u, 1024u> >::Write(bool, unsigned int) ()
#2  0x00000000004113c2 in SyncLoggerTemp<SyncLoggerItemTemp<256u, 4096u, 1024u> >::LogProcessCallBack(void*) ()
#3  0x000000000040cc44 in System::Thread::Routine(void*) ()
#4  0x00000037e9807f05 in start_thread () from /lib64/libpthread.so.0
#5  0x00000037e94d953d in clone () from /lib64/libc.so.6
Thread 6 (Thread 0x7f7c04d74700 (LWP 17675)):
#0  0x00000037e94d9c13 in epoll_wait () from /lib64/libc.so.6
#1  0x00007f7c0a17ac51 in event_handler_manager::thread_loop() () from /usr/lib64/libvma.so
#2  0x00007f7c0a17b416 in event_handler_thread(void*) () from /usr/lib64/libvma.so
#3  0x00000037e9807f05 in start_thread () from /lib64/libpthread.so.0
#4  0x00000037e94d953d in clone () from /lib64/libc.so.6
Thread 5 (Thread 0x7f7bfbfff700 (LWP 17681)):
#0  0x00000037e980be6c in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
#1  0x0000000000417ec5 in FIXCompress::UDPIn<FixForwarder::Controller>::Process() ()
#2  0x0000000000417f69 in FIXCompress::UDPIn<FixForwarder::Controller>::ThreadCallBack(void*) ()
#3  0x000000000040cc44 in System::Thread::Routine(void*) ()
#4  0x00000037e9807f05 in start_thread () from /lib64/libpthread.so.0
#5  0x00000037e94d953d in clone () from /lib64/libc.so.6
Thread 4 (Thread 0x7f7bfb5fe700 (LWP 17682)):
#0  0x00000037e980be6c in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
#1  0x000000000040e2cf in FixForwarder::Client::Terminate() ()
#2  0x000000000040ece8 in FixForwarder::Client::Startup(int) ()
#3  0x0000000000415818 in FixForwarder::Controller::StartClient() ()
#4  0x00000000004158ef in FixForwarder::Controller::ServerProcess() ()
#5  0x0000000000417aa9 in FixForwarder::Controller::ServerCallBack(void*) ()
#6  0x000000000040cc44 in System::Thread::Routine(void*) ()
#7  0x00000037e9807f05 in start_thread () from /lib64/libpthread.so.0
#8  0x00000037e94d953d in clone () from /lib64/libc.so.6
Thread 3 (Thread 0x7f7b8f12c700 (LWP 24605)):
#0  0x00000037e980be6c in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
#1  0x000000000040fae3 in FixForwarder::Client::InboundProcess() ()
#2  0x0000000000412699 in FixForwarder::Client::InboundCallBack(void*) ()
#3  0x000000000040cc44 in System::Thread::Routine(void*) ()
#4  0x00000037e9807f05 in start_thread () from /lib64/libpthread.so.0
#5  0x00000037e94d953d in clone () from /lib64/libc.so.6
Thread 2 (Thread 0x7f7b8e72a700 (LWP 24606)):
#0  0x00000037e980be6c in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
#1  0x0000000000411385 in SyncLoggerTemp<SyncLoggerItemTemp<256u, 4096u, 1024u> >::Write(bool, unsigned int) ()
#2  0x00000000004113c2 in SyncLoggerTemp<SyncLoggerItemTemp<256u, 4096u, 1024u> >::LogProcessCallBack(void*) ()
#3  0x000000000040cc44 in System::Thread::Routine(void*) ()
#4  0x00000037e9807f05 in start_thread () from /lib64/libpthread.so.0
#5  0x00000037e94d953d in clone () from /lib64/libc.so.6
Thread 1 (Thread 0x7f7c09c74740 (LWP 17652)):
#0  0x00000037e980be6c in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
#1  0x000000000040ff90 in System::Thread::Wait(unsigned int) ()
#2  0x00000000004176ee in FixForwarder::Controller::Terminate() ()
#3  0x000000000040c341 in main ()

**Comment by nijinboc** [comment]
HI,
About the server hanging, actually I found that's my problem (there is a race condition in my code which happen more often in multi-core environment).
Sorry about that.
