### ISSUE TITLE
libvma dont work with teamd daemon in centos 7

### ISSUE THREAD

**Issue by sm1ly** [Mellanox/libvma#36]
subj.

 VMA ERROR  : utils:243:priv_read_file() ERROR while opening file /sys/class/net/team1/device/resource (errno 2 No such file or directory)
 VMA ERROR  : utils:484:get_ipv4_from_ifname() Failed getting ipv4 from interface 'eth0' (errno=99 Cannot assign requested address)
 VMA WARNING: rtm:143:rt_mgr_update_source_ip() could not figure out source ip for rtv = dst: 169.254.0.0     netmask: 255.255.0.0     dev: eth0                       table :main       scope 253 type  1 index  2
 VMA ERROR  : utils:484:get_ipv4_from_ifname() Failed getting ipv4 from interface 'team1' (errno=99 Cannot assign requested address)
 VMA WARNING: rtm:143:rt_mgr_update_source_ip() could not figure out source ip for rtv = dst: 169.254.0.0     netmask: 255.255.0.0     dev: team1                      table :main       scope 253 type  1 index  6
 VMA ERROR  : utils:484:get_ipv4_from_ifname() Failed getting ipv4 from interface 'eth0' (errno=99 Cannot assign requested address)
 VMA WARNING: rtm:206:rt_mgr_update_source_ip() could not figure out source ip for rtv = dst: 169.254.0.0     netmask: 255.255.0.0     dev: eth0                       table :main       scope 253 type  1 index  2
 VMA ERROR  : utils:484:get_ipv4_from_ifname() Failed getting ipv4 from interface 'team1' (errno=99 Cannot assign requested address)
 VMA WARNING: rtm:206:rt_mgr_update_source_ip() could not figure out source ip for rtv = dst: 169.254.0.0     netmask: 255.255.0.0     dev: team1                      table :main       scope 253 type  1 index  6
 VMA PANIC  : ring_simple[0x1399df0]:144:create_resources() p_ring_info.p_ib_ctx = NULL. It can be related to wrong bonding configuration
terminate called without an active exception
Aborted

**Comment by rosenbaumalex** [comment]
I'm not familiar with teamd configuration. We'll take a look and then we can update.
1. make sure VMA does not fail, but passes all traffic to OS
2. add to VMA roadmap

In VMA 7.0.8 we added the bonding LAG support (mode=4) https://github.com/Mellanox/libvma/releases/tag/7.0.8

How critical is this for you?
How is the different you gain by team compared to other bond configurations?

**Comment by sm1ly** [comment]
hi. with bonding I got about 500nanoseconds overhead. teamd talks that they got very low overhead and I want to test it with libvma, but I cant.
mode 1 or 4 it doesnt matter. always overhead.

**Comment by rosenbaumalex** [comment]
When you say you got 500ns over head with bond, is that over OS or VMA?

VMA bypasses the kernel fast path with direct HW access from user space. So the fast path is totally different.
Our performance testing with VMA shows negligible difference between bond or direct interface mapping configuration. please update us if you see other ways.

PS: in the kernel you might see a difference between the bond and teamd (we haven't tested this).

**Comment by sm1ly** [comment]
500ns over VMA
what perfomance tests do u use?
so its look like I configure mlnx0.1000 and make test with other server like this configuration I got for example 20000ns
if I configure one of the server and switch (mellanox sx1210) for an lacp or active/backup mode and make test I got test 20500ns. so its look like when I configure bonding on linux - I got overhead.
and this test I always start on both servers like LD_PRELOAD=libvma.so ./test.out

**Comment by sm1ly** [comment]
Okey. I make some more tests.
it looks like this:
we got test1 and test2 servers
test1 always use only one mellanox port and nothing else. its a client.
test2 got 2 ports. one in sx1210_0 second in sx1210_1. switches got ipl configured.
when I write mlnx0 it means it in sx1210_0 where is test1 server are. when I write mlnx1 its means sx1210_1 using mlag port and ipl
if I got only mlnx0 with no mlag and bond - i got 10000ns
next test bond0 on mlnx0 (mode=1(active/backup)), no mlag. its about 10200ns
next test bond0 on mlnx0 (mode=1(active/backup)), mlag static. its about 10300ns
next test bond0 on mlnx1 (mode=1(active/backup)), mlag static. its about 10900-11000ns
next test bond0 on mlnx0 (mode=4(LACP)), mlag LACP. its about 10300-10400ns
next test bond0 on mlnx1 (mode=4(LACP)), mlag LACP. its about 16000ns !!!!!
and the last test.
bond0 on mlnx0+1 (mode=4(LACP)), mlag LACP. its about 10600-10700ns, and traffic goes TO test2 by sx1210_0 and FROM test by sx1210_1
so libvma+bond LACP + ipl got 6000 ns overhead.

**Comment by sm1ly** [comment]
and one more. I maked all this tests with no libvma.
it got overhead like with libvma,but in test bond0 on mlnx1 (mode=4(LACP)), mlag LACP where vma got 6000ns overhead, it giving normal ovehead like other tests. not more that 1000ns

**Comment by orkmellanox** [comment]
Hi,
I am not able to reproduce such overhead using bond configuration.
Can you please check that the traffic is offloaded? (using the vma_stats utility)
If not offloaded, can you attach a log file? (VMA_TRACELEVEL=4 VMA_LOG_FILE=<path_to_log_file>)

Can you test with a public network benchmark tool (like netperf, sockperf https://github.com/mellanox/sockperf ) and tell us:
1. how do you configure the bond interface, what are the exact steps and parameters
2. Is the bond over two NICs, or two ports on one NIC? If two NICs, are they on the same NUMA node?
2. what are the test commands
3. what are the results

I hope that with exact description I will be able to reproduce the issue,

Thanks!

**Comment by rosenbaumalex** [comment]
No update on this for long time after Or could not reproduce.
Close ticket.
