### ISSUE TITLE
Support for connectX4 

### ISSUE THREAD

**Issue by clameter** [Mellanox/libvma#37]
It seems that connectx4 / mlx5 /libmlx5 is not supported for the inbox (upstream) driver and not working on Redhat 7.X. Can that be fixed?

**Comment by rosenbaumalex** [comment]
True. At this point in time you'll need to install MLNX_OFED (3.1-1.0.0 or
newer) to get the ConnectX4 supporteded feature for VMA to work properly.

We're working on closing the mlx5 + libmlx5 feature set and then pushing
all the patches upstream... and immediately into RHEL. We'd like to make it
in time for RHEL7.3 but not sure yet about schedule.

__________________________________
  Alex Rosenbaum  | +972-545-234-555

**Comment by rosenbaumalex** [comment]
Can we close the ticket?

This is not a VMA feature request.
Mellanox is working to push all the required code into kernel and user space to provide the mlx5 support required,

**Comment by clameter** [comment]
Ok.
