### ISSUE TITLE
using VMA seems slower than without

### ISSUE THREAD

**Issue by Robert142** [Mellanox/libvma#371]
Following the instructions on the wiki here:
[https://github.com/Mellanox/libvma/wiki/Example-running-sockperf-ping-pong-test-with-VMA](Example running sockperf ping pong test with VMA)

It seems slower. 
I have one machine with a ConnectX-3.
I run the server with 
```
./sockperf sr
```
and when I run the client with
```
./sockperf pp -i 172.19.216.193 --mc-tx-if 172.19.216.194
```
I get ```Summary: Latency is 5.304 usec``` in the output.

But when I run it with VMA
```
LD_PRELOAD=/lib64/libvma.so.8 ./sockperf pp -i 172.19.216.193 --mc-tx-if 172.19.216.19
```
I get ``` Summary: Latency is 9.039 usec ```

So it's actually almost twice as slow with VMA than without!
Is this an error? or can someone please explain this?

**Comment by OphirMunk** [comment]
Hello @Robert142.
We are not familiar with the issue that you have described. We even tried recreating your scenario unsuccessfully (that is - VMA was always successful in offloading)

A few questions:
1. What is your distribution (RHEL? Ubuntu? what version?)
2. Have you installed OFED driver? 
To print OFED version please execute
```
ofed_info -s
```
Or maybe you haven't installed OFED and you are using VMA inbox drivers (drivers from OS distribution)?
3. Can you send your routing tables? Can you send all IP address assigned to devices?
What IP addresses are assigned to CX3 card?

**Comment by Robert142** [comment]
Thanks for your reply.
I am running on Centos 7.3 and ofed_info -s returns 
mlnx-en-4.0-2.0.0.1:

Running ip addr I get
[root@tregnum mlnx-en-4.0-2.0.0.1-rhel7.3-x86_64]# ip addr
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: eth0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc mq state DOWN qlen 1000
    link/ether 00:25:90:eb:04:ba brd ff:ff:ff:ff:ff:ff
3: eno1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP qlen 1000
    link/ether 00:25:90:eb:04:bb brd ff:ff:ff:ff:ff:ff
    inet 172.19.216.221/24 brd 172.19.216.255 scope global dynamic eno1
       valid_lft 571435sec preferred_lft 571435sec
    inet6 fe80::225:90ff:feeb:4bb/64 scope link
       valid_lft forever preferred_lft forever
8: enp1s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP qlen 1000
    link/ether e4:1d:2d:0b:22:40 brd ff:ff:ff:ff:ff:ff
    inet 172.19.216.194/24 brd 172.19.216.255 scope global enp1s0
       valid_lft forever preferred_lft forever
    inet6 fe80::e61d:2dff:fe0b:2240/64 scope link
       valid_lft forever preferred_lft forever
9: enp1s0d1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP qlen 1000
    link/ether e4:1d:2d:0b:22:41 brd ff:ff:ff:ff:ff:ff
    inet 172.19.216.193/24 brd 172.19.216.255 scope global enp1s0d1
       valid_lft forever preferred_lft forever
    inet6 fe80::e61d:2dff:fe0b:2241/64 scope link
       valid_lft forever preferred_lft forever
[root@tregnum mlnx-en-4.0-2.0.0.1-rhel7.3-x86_64]#

enp1s0 and enp1s0d1 are the Mellanox addresses.

In one terminal I just run 
./sockperf sf
with output
sockperf: == version #2.8-1.git9fbe737a4d29 ==
sockperf: [SERVER] listen on:
[ 0] IP = 0.0.0.0         PORT = 11111 # UDP
sockperf: Warmup stage (sending a few dummy messages)...
sockperf: [tid 5777] using recvfrom() to block on socket(s)
^Csockperf: Test end (interrupted by user)
sockperf: Total 651265 messages received and handled
sockperf: cleanupAfterLoop() exit
[root@tregnum sockperf]#
[root@tregnum sockperf]#
[root@tregnum sockperf]#
[root@tregnum sockperf]# ./sockperf sr
sockperf: == version #2.8-1.git9fbe737a4d29 ==
sockperf: [SERVER] listen on:
[ 0] IP = 0.0.0.0         PORT = 11111 # UDP
sockperf: Warmup stage (sending a few dummy messages)...
sockperf: [tid 4770] using recvfrom() to block on socket(s)

and in a different terminal, I run
[root@tregnum sockperf]# LD_PRELOAD=/lib64/libvma.so.8 ./sockperf pp -i 172.19.216.193 --mc-tx-if 172.19.216.19
 VMA INFO: ---------------------------------------------------------------------------
 VMA INFO: VMA_VERSION: 8.3.1-0 Development Snapshot built on Apr 18 2017 12:03:59
 VMA INFO: Git: 9b02a568059c1c5e91de2f51c000a18ff12e1601
 VMA INFO: Cmd Line: ./sockperf pp -i 172.19.216.193 --mc-tx-if 172.19.216.19
 VMA INFO: Current Time: Wed May  3 12:10:00 2017
 VMA INFO: Pid:  5755
 VMA INFO: Architecture: x86_64
 VMA INFO: Node: tregnum
 VMA INFO: Log Level                      INFO                       [VMA_TRACELEVEL]
 VMA INFO: ---------------------------------------------------------------------------
sockperf: == version #2.8-1.git9fbe737a4d29 ==
sockperf[CLIENT] send on:sockperf: using recvfrom() to block on socket(s)

[ 0] IP = 172.19.216.193  PORT = 11111 # UDP
sockperf: Warmup stage (sending a few dummy messages)...
sockperf: Starting test...
sockperf: Test end (interrupted by timer)
sockperf: Test ended
sockperf: [Total Run] RunTime=1.100 sec; SentMessages=59449; ReceivedMessages=59448
sockperf: ========= Printing statistics for Server No: 0
sockperf: [Valid Duration] RunTime=1.000 sec; SentMessages=54533; ReceivedMessages=54533
sockperf: ====> avg-lat=  9.138 (std-dev=2.081)
sockperf: # dropped messages = 0; # duplicated messages = 0; # out-of-order messages = 0
sockperf: Summary: Latency is 9.138 usec
sockperf: Total 54533 observations; each percentile contains 545.33 observations
sockperf: ---> <MAX> observation =  352.603
sockperf: ---> percentile 99.999 =  332.593
sockperf: ---> percentile 99.990 =   16.946
sockperf: ---> percentile 99.900 =   15.905
sockperf: ---> percentile 99.000 =   10.440
sockperf: ---> percentile 90.000 =    9.189
sockperf: ---> percentile 75.000 =    9.101
sockperf: ---> percentile 50.000 =    9.052
sockperf: ---> percentile 25.000 =    9.010
sockperf: ---> <MIN> observation =    4.512

Whereas without VMA I get
[root@tregnum sockperf]# ./sockperf pp -i 172.19.216.193 --mc-tx-if 172.19.216.194
sockperf: == version #2.8-1.git9fbe737a4d29 ==
sockperf[CLIENT] send on:sockperf: using recvfrom() to block on socket(s)

[ 0] IP = 172.19.216.193  PORT = 11111 # UDP
sockperf: Warmup stage (sending a few dummy messages)...
sockperf: Starting test...
sockperf: Test end (interrupted by timer)
sockperf: Test ended
sockperf: [Total Run] RunTime=1.100 sec; SentMessages=101804; ReceivedMessages=101803
sockperf: ========= Printing statistics for Server No: 0
sockperf: [Valid Duration] RunTime=1.000 sec; SentMessages=92512; ReceivedMessages=92512
sockperf: ====> avg-lat=  5.353 (std-dev=0.494)
sockperf: # dropped messages = 0; # duplicated messages = 0; # out-of-order messages = 0
sockperf: Summary: Latency is 5.353 usec
sockperf: Total 92512 observations; each percentile contains 925.12 observations
sockperf: ---> <MAX> observation =   22.709
sockperf: ---> percentile 99.999 =   17.050
sockperf: ---> percentile 99.990 =   14.794
sockperf: ---> percentile 99.900 =   12.330
sockperf: ---> percentile 99.000 =    7.154
sockperf: ---> percentile 90.000 =    5.468
sockperf: ---> percentile 75.000 =    5.336
sockperf: ---> percentile 50.000 =    5.270
sockperf: ---> percentile 25.000 =    5.224
sockperf: ---> <MIN> observation =    4.004

where can I find this vma_stats program?

**Comment by liranoz12** [comment]
Hi @Robert142,

I didn't manage to reproduce the issue at my environment : Cx3, mlnx-en-4.0-2.0.0., libvma 9b02a56.
I have few questions regarding your setup :
1. Do both server and client run on the same machine?
2. Do you use a VM ?

Please try both sides offloaded as:
1. At server run : `LD_PRELOAD=/lib64/libvma.so.8 ./sockperf sr -i  172.19.216.194`
2. At client run : `LD_PRELOAD=/lib64/libvma.so.8 ./sockperf pp -i  172.19.216.194`
3. Run again both server and client without VMA.

Please attach the output.

To run vma_stat run the following : `vma_stats` (after your application + VMA has started and before it finishes)
P.S Why do you run sockperf client using _--mc-tx-if 172.19.216.194_ when your ip is not multicast ip ?

**Comment by Robert142** [comment]
1)
Yes, I was running the server and client on the same machine.
I did try originally on a different machine, but since I only have one Mellanox card currently to evaluate with I used the one.
2)
No, I'm not using a VM

Running both sides as offloaded, as described I get:
[root@tregnum sockperf]#  LD_PRELOAD=/lib64/libvma.so.8 ./sockperf sr -i 172.19.216.194
 VMA INFO: ---------------------------------------------------------------------------
 VMA INFO: VMA_VERSION: 8.3.1-0 Development Snapshot built on Apr 18 2017 12:03:59
 VMA INFO: Git: 9b02a568059c1c5e91de2f51c000a18ff12e1601
 VMA INFO: Cmd Line: ./sockperf sr -i 172.19.216.194
 VMA INFO: Current Time: Thu May  4 09:48:40 2017
 VMA INFO: Pid: 15157
 VMA INFO: Architecture: x86_64
 VMA INFO: Node: tregnum
 VMA INFO: Log Level                      INFO                       [VMA_TRACELEVEL]
 VMA INFO: ---------------------------------------------------------------------------
sockperf: == version #2.8-1.git9fbe737a4d29 ==
sockperf: [SERVER] listen on:
[ 0] IP = 172.19.216.194  PORT = 11111 # UDP
sockperf: Warmup stage (sending a few dummy messages)...
sockperf: [tid 15157] using recvfrom() to block on socket(s)

and

[root@tregnum sockperf]#  LD_PRELOAD=/lib64/libvma.so.8 ./sockperf pp -i 172.19.216.194
 VMA INFO: ---------------------------------------------------------------------------
 VMA INFO: VMA_VERSION: 8.3.1-0 Development Snapshot built on Apr 18 2017 12:03:59
 VMA INFO: Git: 9b02a568059c1c5e91de2f51c000a18ff12e1601
 VMA INFO: Cmd Line: ./sockperf pp -i 172.19.216.194
 VMA INFO: Current Time: Thu May  4 09:49:17 2017
 VMA INFO: Pid: 15332
 VMA INFO: Architecture: x86_64
 VMA INFO: Node: tregnum
 VMA INFO: Log Level                      INFO                       [VMA_TRACELEVEL]
 VMA INFO: ---------------------------------------------------------------------------
sockperf: == version #2.8-1.git9fbe737a4d29 ==
sockperf[CLIENT] send on:sockperf: using recvfrom() to block on socket(s)

[ 0] IP = 172.19.216.194  PORT = 11111 # UDP
sockperf: Warmup stage (sending a few dummy messages)...
sockperf: Starting test...
sockperf: Test end (interrupted by timer)
sockperf: Test ended
sockperf: [Total Run] RunTime=1.100 sec; SentMessages=311495; ReceivedMessages=311494
sockperf: ========= Printing statistics for Server No: 0
sockperf: [Valid Duration] RunTime=1.000 sec; SentMessages=286694; ReceivedMessages=286694
sockperf: ====> avg-lat=  1.725 (std-dev=1.292)
sockperf: # dropped messages = 0; # duplicated messages = 0; # out-of-order messages = 0
sockperf: Summary: Latency is 1.725 usec
sockperf: Total 286694 observations; each percentile contains 2866.94 observations
sockperf: ---> <MAX> observation =  363.169
sockperf: ---> percentile 99.999 =  106.522
sockperf: ---> percentile 99.990 =   10.253
sockperf: ---> percentile 99.900 =    8.092
sockperf: ---> percentile 99.000 =    3.261
sockperf: ---> percentile 90.000 =    1.793
sockperf: ---> percentile 75.000 =    1.691
sockperf: ---> percentile 50.000 =    1.653
sockperf: ---> percentile 25.000 =    1.614
sockperf: ---> <MIN> observation =    1.453

So this is now showing a speed improvement.

Interestingly though, If I run the server as offloaded and the client not - the client cannot connect.

If I run both the server and client without VMA I get.
Summary: Latency is 5.310 usec
as before, so about 3 times slower.

Thank you.
This seems to answer my query.

**Comment by liranoz12** [comment]
Hi @Robert142,

thanks for your quick response,
I'm glad to hear that I've been able to help.
In order to improve your results you can also use _VMA_SPEC=latency_. this should reduce your  maximum values significantly.
You can also follow  [VMA Performance Tuning Guide](https://community.mellanox.com/docs/DOC-2797) for additional tuning options.


> Interestingly though, If I run the server as offloaded and the client not - the client cannot connect.

This is a known limitation of VMA. you can find it in the release notes.

Thanks,
Liran.

**Comment by Robert142** [comment]
Thanks for the link Liran, an interesting read. 
It's pretty good this VMA library. You've done an excellant job.
