### ISSUE TITLE
802.3ad bonding mode support

### ISSUE THREAD

**Issue by galuha** [Mellanox/libvma#38]
As of VMA 6.6.4, the only bonding supported is the Active/Passive mode, and only with fail_over_mac=1
Is 802.3ad bonding mode support planned? If not, is there any way for us to influence some how and add it to enhancements plan?

**Comment by orkmellanox** [comment]
802.3ad bonding mode is already supported in latest vma (7.0.11)

**Comment by orkmellanox** [comment]
Also, not all configurations are supported, please take a look here:
https://github.com/Mellanox/libvma/wiki/Bonding-configuration

**Comment by galuha** [comment]
That is a good news! Thnx. On mellanox.com the VMA distribution for download is 6.9.1.
I wonder does OFED have old 6.9.1 VMA or newer with bonding mode 4 support?

**Comment by rosenbaumalex** [comment]
MLNX_OFED-3.1-1.xx has the a much newer VMA version 7.0.7.
use '--vma' flag when installing MLNX_OFED to get that VMA auto installed.

You can follow the github to get fastest updates about new releases/tags here: https://github.com/Mellanox/libvma/releases


and we'll update the mellanox.com VMA landing page with this info.
thanks

Alex

**Comment by galuha** [comment]
Thank you
