### ISSUE TITLE
Some TCP client sessions doesn't get offloaded even when the rule in libvma states them to be offloaded

### ISSUE THREAD

**Issue by amittal** [Mellanox/libvma#406]
Hi

I am new to using VMA and was trying to offload a few tcp client session my program makes. I can see those TCP client sessions in lsof and netstat

netstat output
tcp        0      0 <my machine hostname>:44867 220.248.84.82:54305         ESTABLISHED

my libvma rule is
use vma tcp_client 220.248.84.82:*:*:*

I can see in the vma logs that it is picking the rules

Pid: 15692 Tid: 15692 VMA DEBUG: match:248:__vma_print_conf_file() Configuration File:
Pid: 15692 Tid: 15692 VMA DEBUG: match:201:print_instance_id_str() application-id dce_futureTD* B1:
Pid: 15692 Tid: 15692 VMA DEBUG: match:221:print_instance_conf()   tcp_server's rules:
Pid: 15692 Tid: 15692 VMA DEBUG: match:225:print_instance_conf()   tcp_clinet's rules:
Pid: 15692 Tid: 15692 VMA DEBUG: match:191:print_rule()                    use VMA TCP 220.248.84.82:*:*:*
Pid: 15692 Tid: 15692 VMA DEBUG: match:229:print_instance_conf()   udp receiver rules:
Pid: 15692 Tid: 15692 VMA DEBUG: match:233:print_instance_conf()   udp sender rules:
Pid: 15692 Tid: 15692 VMA DEBUG: match:237:print_instance_conf()   udp connect rules:
Pid: 15692 Tid: 15692 VMA DEBUG: match:191:print_rule()                    use OS UDP *:53
Pid: 15692 Tid: 15692 VMA DEBUG: match:240:print_instance_conf()  

But i don't see these tcp sessions offloaded in the vma_stats

Following are the vma logs where libvma is able to capture the socket creation but still can't offload them it seems

ESC[0mESC[0m Pid: 15692 Tid: 15745 VMA DEBUG: ENTER: connect(fd=92, AF_INET, addr=220.248.84.82, port=54303)
ESC[0mESC[0m Pid: 15692 Tid: 15741 VMA DEBUG: si[fd=91]:127:set_blocking() set socket to non-blocking mode
ESC[0mESC[2m Pid: 15692 Tid: 15744 VMA FINER: fdc:211:get() fd=0 Not Found
ESC[0mESC[0m Pid: 15692 Tid: 15741 VMA DEBUG: si[fd=91]:210:ioctl() going to OS for ioctl request=21537, flags=377d4bf8
ESC[0mESC[2m Pid: 15692 Tid: 15740 VMA FINE: select_call:139:select_call() num all offloaded_fds=0
ESC[0mESC[2m Pid: 15692 Tid: 15740 VMA FINER: io_mux_call:480:call() 
ESC[0mESC[2m Pid: 15692 Tid: 15744 VMA FINE: select_call:139:select_call() num all offloaded_fds=0
ESC[0mESC[2m Pid: 15692 Tid: 15745 VMA FINER: fdc:211:get() fd=92 Found
ESC[0mESC[0m Pid: 15692 Tid: 15743 VMA DEBUG: ENTER: connect(fd=93, AF_INET, addr=220.248.84.82, port=54307)
ESC[0mESC[2m Pid: 15692 Tid: 15744 VMA FINER: io_mux_call:480:call() 
ESC[0mESC[2m Pid: 15692 Tid: 15741 VMA FINE: EXIT: ioctl() returned with 0
ESC[0mESC[2m Pid: 15692 Tid: 15743 VMA FINER: fdc:211:get() fd=93 Found
ESC[0mESC[2m Pid: 15692 Tid: 15740 VMA FINE: io_mux_call:63:timer_update() start timer
ESC[0mESC[2m Pid: 15692 Tid: 15745 VMA FINER: si_tcp[fd=92]:2064:bind() 
ESC[0mESC[0m Pid: 15692 Tid: 15741 VMA DEBUG: ENTER: connect(fd=91, AF_INET, addr=220.248.84.82, port=54305)
ESC[0mESC[2m Pid: 15692 Tid: 15741 VMA FINER: fdc:211:get() fd=91 Found
ESC[0mESC[2m Pid: 15692 Tid: 15740 VMA FINE: select_call:254:wait_os() calling os select: 1
ESC[0mESC[2m Pid: 15692 Tid: 15743 VMA FINER: si_tcp[fd=93]:2064:bind() 
ESC[0mESC[0m Pid: 15692 Tid: 15745 VMA DEBUG: si_tcp[fd=92]:2155:bind() socket bound
ESC[0mESC[2m Pid: 15692 Tid: 15740 VMA FINE: io_mux_call:522:call() return 0
ESC[0mESC[2m Pid: 15692 Tid: 15744 VMA FINE: io_mux_call:63:timer_update() start timer
ESC[0mESC[0m Pid: 15692 Tid: 15745 VMA DEBUG: dst[0x7f2a20001380]:56:dst_entry() dst:220.248.84.82:54303 src: 35135
ESC[0mESC[2m Pid: 15692 Tid: 15740 VMA FINE: EXIT: select_helper() readfds: 00000000, writefds: 00000000
ESC[0mESC[0m Pid: 15692 Tid: 15745 VMA DEBUG: dst[0x7f2a20001380]:539:prepare_to_send() 
ESC[0mESC[2m Pid: 15692 Tid: 15744 VMA FINE: select_call:254:wait_os() calling os select: 1
ESC[0mESC[0m Pid: 15692 Tid: 15745 VMA DEBUG: rtm:428:create_new_entry() 
ESC[0mESC[2m Pid: 15692 Tid: 15741 VMA FINER: si_tcp[fd=91]:2064:bind() 
ESC[0mESC[0m Pid: 15692 Tid: 15741 VMA DEBUG: si_tcp[fd=91]:2155:bind() socket bound
ESC[0mESC[0m Pid: 15692 Tid: 15743 VMA DEBUG: si_tcp[fd=93]:2155:bind() socket bound
ESC[0mESC[0m Pid: 15692 Tid: 15741 VMA DEBUG: dst[0x7f2a24001380]:56:dst_entry() dst:220.248.84.82:54305 src: 44867
ESC[0mESC[0m Pid: 15692 Tid: 15743 VMA DEBUG: dst[0x7f2a18001380]:56:dst_entry() dst:220.248.84.82:54307 src: 36207
ESC[0mESC[0m Pid: 15692 Tid: 15745 VMA DEBUG: rrm:167:create_new_entry() 
ESC[0mESC[0m Pid: 15692 Tid: 15743 VMA DEBUG: dst[0x7f2a18001380]:539:prepare_to_send() 
ESC[0mESC[0m Pid: 15692 Tid: 15741 VMA DEBUG: dst[0x7f2a24001380]:539:prepare_to_send() 
ESC[0mESC[2m Pid: 15692 Tid: 15744 VMA FINE: io_mux_call:522:call() return 0
ESC[0mESC[0m Pid: 15692 Tid: 15745 VMA DEBUG: rrm:180:update_entry() entry [0x7f2a20001af0]
ESC[0mESC[0m Pid: 15692 Tid: 15745 VMA DEBUG: rrm:185:update_entry() rule_entry is not valid-> update value
ESC[0mESC[2m Pid: 15692 Tid: 15744 VMA FINE: EXIT: select_helper() readfds: 00000000, writefds: 00000000
ESC[0mESC[2m Pid: 15692 Tid: 15740 VMA FINE: ENTER: select(nfds=1, timeout=(0 sec, 0 usec))
ESC[0mESC[2m Pid: 15692 Tid: 15744 VMA FINE: ENTER: select(nfds=1, timeout=(0 sec, 0 usec))
ESC[0mESC[2m Pid: 15692 Tid: 15740 VMA FINE: srdr:1630:select_helper() readfds: 00000000, writefds: 00000000
ESC[0mESC[2m Pid: 15692 Tid: 15744 VMA FINE: srdr:1630:select_helper() readfds: 00000000, writefds: 00000000
ESC[0mESC[0m Pid: 15692 Tid: 15745 VMA DEBUG: rre[Destination IP:220.248.84.82]:54:get_val() 
ESC[0mESC[2m Pid: 15692 Tid: 15744 VMA FINER: fdc:211:get() fd=0 Not Found
ESC[0mESC[2m Pid: 15692 Tid: 15745 VMA FINE: rrm:202:find_rule_val() destination info :
ESC[0mESC[2m Pid: 15692 Tid: 15740 VMA FINER: fdc:211:get() fd=0 Not Found
ESC[0mESC[2m Pid: 15692 Tid: 15740 VMA FINE: select_call:139:select_call() num all offloaded_fds=0
ESC[0mESC[0m Pid: 15692 Tid: 15745 VMA DEBUG: rrm:190:update_entry() ERROR: could not find rule val for rule_entry 'Destination IP:220.248.84.82'
ESC[0mESC[2m Pid: 15692 Tid: 15744 VMA FINE: select_call:139:select_call() num all offloaded_fds=0

I am not sure why its not able to offload them, Does anyone has any idea ?

Thanks
Aashish

**Comment by ilansmith** [comment]
Hi,

Please consulted the [VMA Installation Guide](http://www.mellanox.com/related-docs/prod_acceleration_software/VMA_8_3_5_Installation_Guide.pdf) to make sure you have VMA and all per-requisites installed correctly. See section section 3 (_Running VMA_) for usage examples.

Specifically, it will be useful if you can share information re. the NICs you're using, your Mellanox OFED version and the VMA command line and header.

**Comment by amittal** [comment]
03:00.0 Ethernet controller: Mellanox Technologies MT27520 Family [ConnectX-3 Pro]
Mellanox version :  VMA INFO: VMA_VERSION: 8.2.10-0 Release built on Mar 28 2017 10:27:46
VMA INFO: OFED Version: OFED-internal-4.0-2.0.0:

I checked the installation, it seems to be good.. sample programs seems to be working. Even for my program, TCP server seems to be getting offloaded as per vma_stats (haven't compared its performance). But my tcp client sessions are not getting offloaded by VMA lib.

Log where it intercepts the connect tcp call and bind call but still doesn't offload it.

ESC[0mESC[0m Time:   550.827 Pid: 14620 Tid: 14673 VMA DEBUG: ENTER: connect(fd=93, AF_INET, addr=220.248.84.82, port=54303)
ESC[0mESC[2m Time:   550.831 Pid: 14620 Tid: 14673 VMA FINER: fdc:211:get() fd=93 Found
ESC[0mESC[2m Time:   550.858 Pid: 14620 Tid: 14673 VMA FINER: si_tcp[fd=93]:2064:bind() 
ESC[0mESC[0m Time:   550.897 Pid: 14620 Tid: 14673 VMA DEBUG: si_tcp[fd=93]:2155:bind() socket bound
ESC[0mESC[0m Time:   550.908 Pid: 14620 Tid: 14673 VMA DEBUG: dst[0x7fd618001380]:56:dst_entry() dst:220.248.84.82:54303 src: 51489
ESC[0mESC[0m Time:   550.914 Pid: 14620 Tid: 14673 VMA DEBUG: dst[0x7fd618001380]:539:prepare_to_send() 
ESC[0mESC[0m Time:   550.932 Pid: 14620 Tid: 14673 VMA DEBUG: rtm:428:create_new_entry() 
ESC[0mESC[0m Time:   550.973 Pid: 14620 Tid: 14673 VMA DEBUG: rrm:167:create_new_entry() 
ESC[0mESC[0m Time:   550.977 Pid: 14620 Tid: 14673 VMA DEBUG: rrm:180:update_entry() entry [0x7fd618001af0]
ESC[0mESC[0m Time:   551.005 Pid: 14620 Tid: 14673 VMA DEBUG: rrm:185:update_entry() rule_entry is not valid-> update value
ESC[0mESC[0m Time:   551.010 Pid: 14620 Tid: 14673 VMA DEBUG: rre[Destination IP:220.248.84.82]:54:get_val() 
ESC[0mESC[2m Time:   551.022 Pid: 14620 Tid: 14673 VMA FINE: rrm:202:find_rule_val() destination info :
ESC[0mESC[0m Time:   551.026 Pid: 14620 Tid: 14673 VMA DEBUG: rrm:190:update_entry() ERROR: could not find rule val for rule_entry 'Destination IP:220.248.84.82'
ESC[0mESC[0m Time:   551.035 Pid: 14620 Tid: 14673 VMA DEBUG: rrm:171:create_new_entry() new entry 0x7fd618001af0 created successfully
ESC[0mESC[0m Time:   551.064 Pid: 14620 Tid: 14673 VMA DEBUG: cache_subject_observer:283:register_observer() Created new cache_entry Key = Destination IP:220.248.84.82
ESC[0mESC[0m Time:   551.073 Pid: 14620 Tid: 14673 VMA DEBUG: rtm:353:update_entry() entry [0x7fd618001990]
ESC[0mESC[0m Time:   551.079 Pid: 14620 Tid: 14673 VMA DEBUG: rtm:356:update_entry() route_entry is not valid-> update value
ESC[0mESC[0m Time:   551.090 Pid: 14620 Tid: 14673 VMA DEBUG: rre[Destination IP:220.248.84.82]:54:get_val() 
ESC[0mESC[0m Time:   551.101 Pid: 14620 Tid: 14673 VMA DEBUG: rtm:397:update_entry() rule entry is not valid
ESC[0mESC[0m Time:   551.107 Pid: 14620 Tid: 14673 VMA DEBUG: rtm:432:create_new_entry() new entry 0x7fd618001990 created successfully
ESC[0mESC[0m Time:   551.112 Pid: 14620 Tid: 14673 VMA DEBUG: cache_subject_observer:283:register_observer() Created new cache_entry Key = Destination IP:220.248.84.82
ESC[0mESC[0m Time:   551.119 Pid: 14620 Tid: 14673 VMA DEBUG: rte[]:75:get_val() 
ESC[0mESC[0m Time:   551.125 Pid: 14620 Tid: 14673 VMA DEBUG: rte[]:75:get_val() 
ESC[0mESC[0m Time:   551.137 Pid: 14620 Tid: 14673 VMA DEBUG: dst[0x7fd618001380]:213:update_rt_val() Route entry is not valid
ESC[0mESC[0m Time:   551.140 Pid: 14620 Tid: 14673 VMA DEBUG: dst[0x7fd618001380]:574:prepare_to_send() dst_entry is NOT offloaded!
ESC[0mESC[0m Time:   551.170 Pid: 14620 Tid: 14673 VMA DEBUG: si_tcp[fd=93]:1992:connect() non offloaded socket --> connect only via OS

**Comment by DanielLibenson** [comment]
Hi,

Please try to run a sockperf ping-pong test to be sure that the relevant interface is running correctly, with and without VMA. See [VMA Basic Sockperf test Examples](https://github.com/Mellanox/libvma/wiki/A-VMA-Basic-Sockperf-test-Examples
) for more details.

Could you also please attach a full VMA log file, and if it possible please attach your program code or the relevant parts of that code?

**Comment by NirNitzani** [comment]
Hi @amittal ,
 If more supported is needed please open the thread
