### ISSUE TITLE
libvma seemingly enabled only on IB connections not RoCE. feature or misconfiguration?

### ISSUE THREAD

**Issue by markos** [Mellanox/libvma#41]
hi all,
I think the subject says it all, but to clarify, we have a setup with 2 RoCE + 2 IB connections per node. We tried to use libvma (both preloaded and using the extra API) on the system, but it would fail everytime it tried to register the rdma devices when we used only the RoCE connections, it did however seemed to be enabled when the IB ports were connected as well. Please confirm if this is the case as it was a bit unclear in both the library documentation and the VMA user guide on Mellanox's site. However, even if it appeared to be enabled, we still have problems using it successfully and we can't get either the tests nor our own application -using VMA extra API- work.

**Comment by markos** [comment]
to be more specific, here's what a trace gave me for my interfaces:
Pid: 97228 Tid: 97228 VMA DEBUG: ndtm[0x23f5170]:190:map_net_devices() Blocking offload: No verbs context in cma_id on interfaces ('lo')
Pid: 97228 Tid: 97228 VMA DEBUG: ndtm[0x23f5170]:143:map_net_devices() Checking if can offload on interface 'eth0' (addr=172.22.154.231, flags=11043)
Pid: 97228 Tid: 97228 VMA DEBUG: ndtm[0x23f5170]:179:map_net_devices() Failed in rdma_bind_addr (src=172.22.154.231) (errno=19 No such device)
Pid: 97228 Tid: 97228 VMA DEBUG: ndtm[0x23f5170]:143:map_net_devices() Checking if can offload on interface 'eth4' (addr=10.100.154.231, flags=11043)
Pid: 97228 Tid: 97228 VMA DEBUG: ndtm[0x23f5170]:179:map_net_devices() Failed in rdma_bind_addr (src=10.100.154.231) (errno=19 No such device)
Pid: 97228 Tid: 97228 VMA DEBUG: ndtm[0x23f5170]:143:map_net_devices() Checking if can offload on interface 'eno1' (addr=192.168.1.1, flags=11043)
Pid: 97228 Tid: 97228 VMA DEBUG: ndtm[0x23f5170]:179:map_net_devices() Failed in rdma_bind_addr (src=192.168.1.1) (errno=19 No such device)
Pid: 97228 Tid: 97228 VMA DEBUG: ndtm[0x23f5170]:143:map_net_devices() Checking if can offload on interface 'em2' (addr=172.23.154.231, flags=11043)
Pid: 97228 Tid: 97228 VMA DEBUG: ndtm[0x23f5170]:179:map_net_devices() Failed in rdma_bind_addr (src=172.23.154.231) (errno=19 No such device)
Pid: 97228 Tid: 97228 VMA DEBUG: ndtm[0x23f5170]:143:map_net_devices() Checking if can offload on interface 'ib0' (addr=192.168.100.1, flags=11043)
Pid: 97228 Tid: 97228 VMA FINE: utils:409:get_iftype_from_ifname() find interface type for ifname 'ib0'

Of these, eno1/em2 are RoCE connections, and ib0 is IB. This is the only one that seemed to not fail.
(using libvma 7.0.14 btw).

**Comment by markos** [comment]
on the same page, trying to run either tcp_zcopy_cb, udp_lat or our own code using libvma, we get the following error:
Pid: 97605 Tid: 97605 VMA ERROR: rfs[0x25c65b0]:252:create_ibv_flow() Create of QP flow ID failed with flow dst:192.168.100.1:9007, src:0.0.0.0:0, protocol:UDP (errno=0 - Success)
Pid: 97605 Tid: 97605 VMA ERROR: si[fd=19]:427:attach_receiver() Failed to attach dst:192.168.100.1:9007, src:0.0.0.0:0, protocol:UDP, local if:192.168.100.1 to ring 0x25c9430

udp_lat segfaults

**Comment by rosenbaumalex** [comment]
Hi Makros,  

Let's work on the issues one at a time.

1. Please add information about the NIC type, FW and OFED versions installed.

2. I see you're using 'udp_lat'. That's a tool we stopped maintaining long ago. Currently we're working with [sockperf](https://github.com/mellanox/sockperf) which is udp_lat's successor. 

3. Best is if you install your machine with the latest MLNX_OFED with 'mlnxofedinstall --vma'. Then you'll get latest Mellanox NIC drivers, auto update FW to latest, libvma, and a recent sockperf all installed on your Linux.
Download and install latest VMA as part of [MLNX_OFED GA package from Mellanox.com](http://www.mellanox.com/page/products_dyn?product_family=26&mtag=linux_sw_drivers).  

4. Flow steering failure you see is usually related to wrong config, old firmware install on your NIC, or just an old NIC which does not support the latest flow steering requirements of VMA.

5. VMA over ConnectX3 should support IB and RoCE (RAW QP), whatever you like on any port. I'm guessing you have a ConnectX3 by the questions you raised.

**Comment by rosenbaumalex** [comment]
try (or check it's already set)
```
echo options mlx4_core log_num_mgm_entry_size=-1 >> /etc/modprobe.d/mlnx.conf
```
and restart the driver
```
/etc/init.d/network restart
```

this sets the ConnectX3 driver into Flow Steering mode enabled.
the 'mlnxofedinstall --vma' does this for you.

**Comment by markos** [comment]
1 and 3.
Output of mstflint -d 02:00.0 q:
Image type:      FS2
FW Version:      2.35.5100
FW Release Date: 6.9.2015
Product Version: 02.35.51.00
Rom Info:        type=PXE version=3.4.648 devid=4103
Device ID:       4103
Description:     Node             Port1            Port2            Sys image
GUIDs:           ffffffffffffffff ffffffffffffffff ffffffffffffffff ffffffffffffffff 
MACs:                                 f452145ebdc0     f452145ebdc1
VSD:             
PSID:            MT_1200111023

Same on both devices (only MACs differ). And from what I checked they use both latest firmware.

OFED is not from Mellanox site but the packages already existing in Ubuntu repository (1.0.6-1ubuntu2, which are just packaged versions of upstream openfabrics.org release), I'm running 16.04 at the moment (which will be the next LTS, currently running 4.3.0-6-generic). I did try to build the OFED distro using:

# ./mlnxofedinstall --with-vma -vvv --skip-distro-check --without-dkms --force

and for many packages (but not all) I was able to fix the minor warnings (most compiler warning due to stricted gcc in 16.04). But after I saw that most/all the packages were already part of the distro (apart from libvma), and since everything seemed to be working, I decided to try libvma on its own. I expect 16.04 will be supported when it's released, but since that's not long from now (just 3 months), I decided against installing a 2y old release and try it out. Disclaimer: I'm quite comfortable trying new stuff being a Debian developer myself so this was not a problem, and apart from libvma I had no other issues so far with it.

2. Ok, I will try sockperf instead of udp_lat, once I can establish that VMA is enabled on the setup.

4. The mlx4_core module option was already enabled.

Please advise, is libvma completely impossible to run on the current setup (16.04) and I have to rollback to a previous release? I'd rather not, since I would have to redo this process soon anyway.

**Comment by rosenbaumalex** [comment]
You've got the ConnectX-3 Pro, dual port 10GbE, and yes, your FW seem to be the latest which is required to support VMA in 7.0.x.
And you checked the configuration parameter.

So it seems the only missing part is driver support compatibility.

We did not try to run VMA on inbox Ubuntu drives recently. But we do regular tests of the MLNX_OFED package on them. 

Mellanox is working constantly to push all code upstream, but it takes time. 
I need to check what's the latest on inbox Ubuntu releases and if it answers VMA requirements.

So to get things working quickly I would recommend that you install an Ubuntu which is supported by the latest [MLNX_OFED web page](http://www.mellanox.com/page/products_dyn?product_family=26&mtag=linux_sw_drivers).

PS: We just posted this wiki page about running VMA on top of RHEL-7.2 with inbox drivers.
https://github.com/Mellanox/libvma/wiki/VMA-over-RHEL-7.2-with-inbox-driver

**Comment by markos** [comment]
Hi Alex,
Thank you for your suggestions. I suspect by supporting RHEL 7.2 inbox drivers that also means it supports the -equivalent- CentOS 7.2 as well. Unless you could verify that it's an easy fix for latest Ubuntu :)
I will discuss the options with my team on what is best.

**Comment by rosenbaumalex** [comment]
Yes, CentOS-7.2 is the same. 
I think we noticed small change in how to get the prerequisites libraries installed. 
But the VMA part is identical.

We've started looking into the issue you saw with Ubuntu 16.04. 
I hope we'll map this quickly and be able to push updates in time to make it work with latest VMA before the release.

**Comment by markos** [comment]
Ok, with ubuntu 14.04:
```
# sockperf tp --tcp -i 192.168.1.1 -m 100
sockperf: == version #2.5.254 == 
sockperf[CLIENT] send on:
[ 0] IP = 192.168.1.1     PORT = 11111 # TCP
sockperf: Warmup stage (sending a few dummy messages)...
sockperf: Starting test...
sockperf: Test end (interrupted by timer)
sockperf: Test ended
sockperf: Total of 3090039 messages sent in 1.100 sec

sockperf: NOTE: test was performed, using msg-size=100. For getting maximum throughput consider using --msg-size=1472
sockperf: Summary: Message Rate is 2809108 [msg/sec]
sockperf: Summary: BandWidth is 267.897 MBps (2143.179 Mbps)

# LD_PRELOAD=/usr/lib64/libvma.so sockperf tp --tcp -i 192.168.1.1 -m 100
 VMA INFO   : ---------------------------------------------------------------------------
 VMA INFO   : VMA_VERSION: 7.0.7-0 Release built on 2015-09-08-13:24:18
 VMA INFO   : Cmd Line: sockperf tp --tcp -i 192.168.1.1 -m 100
 VMA INFO   : OFED Version: MLNX_OFED_LINUX-3.1-1.0.3:
 VMA INFO   : Log Level                      3                          [VMA_TRACELEVEL]
 VMA INFO   : ---------------------------------------------------------------------------
sockperf: == version #2.5.254 == 
sockperf[CLIENT] send on:
[ 0] IP = 192.168.1.1     PORT = 11111 # TCP
sockperf: Warmup stage (sending a few dummy messages)...
sockperf: Starting test...
sockperf: Test end (interrupted by timer)
sockperf: Test ended
sockperf: Total of 12168665 messages sent in 1.100 sec

sockperf: NOTE: test was performed, using msg-size=100. For getting maximum throughput consider using --msg-size=1472
sockperf: Summary: Message Rate is 11062429 [msg/sec]
sockperf: Summary: BandWidth is 1054.995 MBps (8439.964 Mbps)
```

As expected. Thanks. I'll following the progress to see when Ubuntu 16.04 will be supported officially -preferably with inbox drivers as well. I'd leave the issue however as a reminder that it needs fixing for 16.04 :)

**Comment by rosenbaumalex** [comment]
can I close this ticket?

**Comment by markos** [comment]
I'd leave it open as reminder for 16.04 support, we can close it as soon as we test it on that.

**Comment by liranoz12** [comment]
@markos, any update ?

**Comment by markos** [comment]
@liranoz12, sorry I do not work on this anymore, and have no access to Mellanox hardware currently to test.

**Comment by NirNitzani** [comment]
Since  Ubuntu 16.04 is supported I assume we can close it - we can reopen if any issue still exists

**Comment by rcroucher** [comment]
We're having exactly the same problem with the inbox libvma drivers for RHEL 7.3.   
Does not work across RoCE.  I'm unable to test InfiniBand.  
Similar warnings given, then fails to make a connection.


VMA WARNING: ib_ctx_collection82:map_ib_devices() Failure in rdma_get_devices() (error=19 No such device)
 VMA WARNING: ib_ctx_collection83:map_ib_devices() Please check OFED installation

Installing MLNX_OFED is not an option since it will taint the kernel and invalidate our Redhat support.  The whole point of the inbox VMA drivers was meant to be so we avoid this tainting.

I thought  one of the goals with RH7.3 was that it 'just worked'  out of the box.  Seems not,  not with a  just a 'yum install libvma'   anyway.

**Comment by rcroucher** [comment]
Created new issue as this one has been closed
