### ISSUE TITLE
Data loss seen with libvma API -  data returned by vma_packet->iovec is less than the value returned by recvfrom_copy

### ISSUE THREAD

**Issue by vikramsc** [Mellanox/libvma#43]
Hi,

I’ve written a client server program using libvma.so. We are seeing data loss when data transferred using recvfrom_zcopy libvma API.

Explanation:

**client_vma code**
Client program which accepts, server IP address, port, buffer size, number of buffers  and interval between buffers sent (in micro secs). 

	$ ./client_vma
	usage ./client_vma <hostname> <port> <bufsize> <bufcount> <sleepinmicro>

	Example: Following client will connect to server 19.1.1.0:9000 and will send buffers of size 4096 to server 100 times with time interval of 10 micro seconds.
		./client_vma “19.1.1.0” 9000 4096 100 10

**server_svm code**
Server program which accepts IP address and port. Internally it uses recvfrom_zcopy() API of libvma whenever it receives data event.  Server calculates the total amount of data received from the client and prints it.

Amount of data received are calculated in 2 ways:
1. Data length based on return value
  	return value from recvfrom_zcopy is the total data len represented by iovec segments in vma_packets  
2. Data length based on iovec
	For each received vma_packet Iterate through iovec and calculate total length of data by adding up all iov[i].io_len

Both of the above value expected to be same. But based on experiment in our lab, we found that, some times the recvfrom_zopy returns correct number data bytes, but corresponding vma_packets has iovec with less number of data bytes.

```C
<Server_vma>
$ export VMA_MTU=9000; export LD_PRELOAD=/usr/lib64/libvma.so; ./server_vma 192.168.1.1 8000
 VMA INFO: ---------------------------------------------------------------------------
 VMA INFO: VMA_VERSION: 7.0.14-0 Release built on Jan 28 2016 20:41:00
 VMA INFO: Cmd Line: ./server_vma 192.168.1.1 8000
 VMA INFO: OFED Version: MLNX_OFED_LINUX-3.2-1.0.1.1:
 VMA INFO: Log Level                      INFO                       [VMA_TRACELEVEL]
 VMA INFO: Rx Mem Bufs                    500000                     [VMA_RX_BUFS]
 VMA INFO: Select Poll (usec)             -1                         [VMA_SELECT_POLL]
 VMA INFO: CQ Interrupts Moderation       Disabled                   [VMA_CQ_MODERATION_ENABLE]
 VMA INFO: CQ Adaptive Moderation         Disabled                   [VMA_CQ_AIM_INTERVAL_MSEC]
 VMA INFO: MTU                            9000                       [VMA_MTU]
 VMA INFO: ---------------------------------------------------------------------------
 VMA WARNING: ndv104:configure() Mismatch between interface eth1 MTU=1500 and VMA_MTU=9000. Make sure VMA_MTU and all offloaded interfaces MTUs match.
Accepted connection on descriptor 23 (host=192.168.1.2, port=47401)
Total Data Recieved [socketfd: 23]: Based on iovec: 2920 bytes,  Based on return value: 2920 bytes
Total Data Recieved [socketfd: 23]: Based on iovec: 4380 bytes,  Based on return value: 4380 bytes
Total Data Recieved [socketfd: 23]: Based on iovec: 7300 bytes,  Based on return value: 7300 bytes
Total Data Recieved [socketfd: 23]: Based on iovec: 8760 bytes,  Based on return value: 8760 bytes
Total Data Recieved [socketfd: 23]: Based on iovec: 13140 bytes,  Based on return value: 13140 bytes
Total Data Recieved [socketfd: 23]: Based on iovec: 14600 bytes,  Based on return value: 14600 bytes
Total Data Recieved [socketfd: 23]: Based on iovec: 21900 bytes,  Based on return value: 21900 bytes
Total Data Recieved [socketfd: 23]: Based on iovec: 23360 bytes,  Based on return value: 23360 bytes
Total Data Recieved [socketfd: 23]: Based on iovec: 32120 bytes,  Based on return value: 32120 bytes
Total Data Recieved [socketfd: 23]: Based on iovec: 33580 bytes,  Based on return value: 33580 bytes
Total Data Recieved [socketfd: 23]: Based on iovec: 43800 bytes,  Based on return value: 43800 bytes
Total Data Recieved [socketfd: 23]: Based on iovec: 45260 bytes,  Based on return value: 45260 bytes
Total Data Recieved [socketfd: 23]: Based on iovec: 52560 bytes,  Based on return value: 52560 bytes
Total Data Recieved [socketfd: 23]: Based on iovec: 56940 bytes,  Based on return value: 56940 bytes
Total Data Recieved [socketfd: 23]: Based on iovec: 58400 bytes,  Based on return value: 58400 bytes
Total Data Recieved [socketfd: 23]: Based on iovec: 67160 bytes,  Based on return value: 67160 bytes
Total Data Recieved [socketfd: 23]: Based on iovec: 71540 bytes,  Based on return value: 71540 bytes
Total Data Recieved [socketfd: 23]: Based on iovec: 73000 bytes,  Based on return value: 73000 bytes
**## ERROR: Datalen from vma_packet's iovec: 6161 != Return value from recvfrom_zcopy: 8920 !!!**
Total Data Recieved [socketfd: 23]: Based on iovec: 79161 bytes,  Based on return value: 81920 bytes
</Server>
```

Above text prefixed with "##ERROR" is printed only if the data length returned by recvfrom_zopy does not match the data provided by corresponding vma_packets.

```C
<Client_vma>
$ export LD_PRELOAD=/usr/lib64/libvma.so; ./client_vma 192.168.1.1 8000 4096 20  10
 VMA INFO: ---------------------------------------------------------------------------
 VMA INFO: VMA_VERSION: 7.0.14-0 Release built on Jan 28 2016 20:41:00
 VMA INFO: Cmd Line: ./client_vma 192.168.1.1 8000 4096 20 10
 VMA INFO: OFED Version: MLNX_OFED_LINUX-3.2-1.0.1.1:
 VMA INFO: Log Level                      INFO                       [VMA_TRACELEVEL]
 VMA INFO: ---------------------------------------------------------------------------
Buf[0] sent (Total data sent: 4096)
Buf[1] sent (Total data sent: 8192)
Buf[2] sent (Total data sent: 12288)
Buf[3] sent (Total data sent: 16384)
Buf[4] sent (Total data sent: 20480)
Buf[5] sent (Total data sent: 24576)
Buf[6] sent (Total data sent: 28672)
Buf[7] sent (Total data sent: 32768)
Buf[8] sent (Total data sent: 36864)
Buf[9] sent (Total data sent: 40960)
Buf[10] sent (Total data sent: 45056)
Buf[11] sent (Total data sent: 49152)
Buf[12] sent (Total data sent: 53248)
Buf[13] sent (Total data sent: 57344)
Buf[14] sent (Total data sent: 61440)
Buf[15] sent (Total data sent: 65536)
Buf[16] sent (Total data sent: 69632)
Buf[17] sent (Total data sent: 73728)
Buf[18] sent (Total data sent: 77824)
Buf[19] sent (Total data sent: 81920)
**##Overall Total data sent = 81920 bytes**
```

**Comment by vikramsc** [comment]
Pasting error log from the server_svm log:

```C
## ERROR: Datalen from vma_packet's iovec: 6161 != Return value from recvfrom_zcopy: 8920 !!!
```
8920 bytes is the value returned by recvfrom_zopy. So same number of bytes would be expected from the vma_packets_t returned by this call. But when total data length calculated by looping through iovec fom each of these vma_packet, it comes up to 6161.
Issue is seen consistently specifically for the last buffer received from the client.

Below, I have attached the source code. See client_svm.c and server_svm.c.
 
[vma_examples.tar.gz](https://github.com/Mellanox/libvma/files/137888/vma_examples.tar.gz)

**Comment by vikramsc** [comment]
Few points to mention:

- The same code works if I add a sleep of 1 second between two consecutive packets transmissions from client. 
- The data loss is seen only for the last packet received by the server.

Also please check if API being used properly. We are trying to use Libvma library for rdma data transfer for our product, and we are stuck here. Please respond as soon as possible.

**Comment by vikramsc** [comment]
I have re-run the test again & collected vma_stat logs with -v3 (verbose) option. Attached the tar containing stats log.

[vmalog.gz](https://github.com/Mellanox/libvma/files/140310/vmalog.gz)

**Comment by vikramsc** [comment]
I have re-run the test again & collected vma_stat logs with -v3 (verbose) option. Attached the tar containing stats log.
[vmalog.gz](https://github.com/Mellanox/libvma/files/140347/vmalog.gz)

**Comment by vikramsc** [comment]
I have re-run the test again & collected vma_stat logs with -v3 (verbose) option. Attached the tar containing stats log.

[vmalog.gz](https://github.com/Mellanox/libvma/files/140310/vmalog.gz)

**Comment by rosenbaumalex** [comment]
thanks for reporting.
we'll take a look in parallel to the other zcopy ticket you've opened.

**Comment by OphirMunk** [comment]
Fixed. Please pull latest github version and re-compile
I have also updated server_vma.c (attached) to be aligned with the fix.
The root cause was that in case of multiple rx packets user buf offsets were wrongly calculated.
With a single rx packet everything worked as expected and this is why the issue was not reproduced when client sending interval was 1 second.

[server_vma.tar.gz](https://github.com/Mellanox/libvma/files/163241/server_vma.tar.gz)

**Comment by OphirMunk** [comment]
I am considering adding your demo application server_vma.c and client_vma.c into VMA wiki.
Thanks for your cooperation.

**Comment by veerals123** [comment]
Has the issue been fixed?



On Tue, Mar 8, 2016 at 6:07 AM -0800, "Ophir Munk" <notifications@github.com<mailto:notifications@github.com>> wrote:


Closed #43<https://github.com/Mellanox/libvma/issues/43>.

-

**Comment by veerals123** [comment]
No problem. Feel free to add.



On Tue, Mar 8, 2016 at 6:05 AM -0800, "Ophir Munk" <notifications@github.com<mailto:notifications@github.com>> wrote:


I am considering adding your demo application server_vma.c and client_vma.c into VMA wiki.
Thanks for your cooperation.

-

**Comment by OphirMunk** [comment]
Issue fixed. Please read a few comments above (server_vma.c updated as well)
