### ISSUE TITLE
test

### ISSUE THREAD

**Issue by mellanoxer** [Mellanox/libvma#44]
del

**Comment by mellanoxer** [comment]
What is the reason to set fail_over_mac=0 in mode=4 (802.3ad) as described here https://github.com/Mellanox/libvma/wiki/Bonding-configuration

if fail_over_mac make sense only in mode=1 (active-backup) as described here https://www.kernel.org/doc/Documentation/networking/bonding.txt
?

**Comment by rosenbaumalex** [comment]
I guess you managed to solve issue quickly :)
