### ISSUE TITLE
Data loss seen with libvma API - callback API vma_recv_callback_t

### ISSUE THREAD

**Issue by vikramsc** [Mellanox/libvma#45]
Data loss seen with libvma callback API: vma_recv_callback_t

I've written client & server program which uses libvma APIs.

Client code: Connects to servers by opening socket using server IP and port number. Sends data over the socket. To use libvma.so did LD_PRELOAD of libvma.so library

Server Code: Server initializes vma_api and registers callback server_vma_recv_callback, which counts number of bytes recieved in by iovecs & prints them in total with the packet id. And also prints total data recieved till now from the client. Then returns VMA_PACKET_RECV.
```c
Callback: Recieved VMA packet 0x7f5787df1a98 containing data of length: 1460, Total data recieved until now: 23360
```
Packets are zero copied using recvfrom_zcopy whenever epool data event is raised for the packet. It also prints the packet ID and length of the data vma packet points to (using iovec).

```c
recvfrom_zcopy: Packet_id: 0x7f5787df0d78 datalen: 2920
```

Following are the Server logs. 

```c
$ export VMA_MTU=9000; export LD_PRELOAD=/usr/lib64/libvma.so; ./server_vma_cb 192.168.1.1 8000
 VMA INFO: ---------------------------------------------------------------------------
 VMA INFO: VMA_VERSION: 7.0.14-0 Release built on Jan 28 2016 20:41:00
 VMA INFO: Cmd Line: ./server_vma_cb 192.168.1.1 8000
 VMA INFO: OFED Version: MLNX_OFED_LINUX-3.2-1.0.1.1:
 VMA INFO: Log Level                      INFO                       [VMA_TRACELEVEL]
 VMA INFO: MTU                            9000                       [VMA_MTU]
 VMA INFO: ---------------------------------------------------------------------------
 VMA WARNING: ndv104:configure() Mismatch between interface eth1 MTU=1500 and VMA_MTU=9000. Make sure VMA_MTU and all offloaded interfaces MTUs match.
Accepted connection on descriptor 23 (host=192.168.1.2, port=51494)
callback registered
Callback: Recieved VMA packet 0x7f5787df0a30 containing data of length: 2920, Total data recieved until now: 2920
recvfrom_zcopy: Packet_id: 0x7f5787df0a30 datalen: 2920
Callback: Recieved VMA packet 0x7f5787df0c60 containing data of length: 1460, Total data recieved until now: 4380
recvfrom_zcopy: Packet_id: 0x7f5787df0c60 datalen: 1460
Callback: Recieved VMA packet 0x7f5787df0d78 containing data of length: 2920, Total data recieved until now: 7300
recvfrom_zcopy: Packet_id: 0x7f5787df0d78 datalen: 2920
Callback: Recieved VMA packet 0x7f5787df0fa8 containing data of length: 1460, Total data recieved until now: 8760
recvfrom_zcopy: Packet_id: 0x7f5787df0fa8 datalen: 1460
Callback: Recieved VMA packet 0x7f5787df10c0 containing data of length: 4380, Total data recieved until now: 13140
recvfrom_zcopy: Packet_id: 0x7f5787df10c0 datalen: 4380
Callback: Recieved VMA packet 0x7f5787df1408 containing data of length: 1460, Total data recieved until now: 14600
recvfrom_zcopy: Packet_id: 0x7f5787df1408 datalen: 1460
Callback: Recieved VMA packet 0x7f5787df1520 containing data of length: 7300, Total data recieved until now: 21900
recvfrom_zcopy: Packet_id: 0x7f5787df1520 datalen: 7300
Callback: Recieved VMA packet 0x7f5787df1a98 containing data of length: 1460, Total data recieved until now: 23360
recvfrom_zcopy: Packet_id: 0x7f5787df1a98 datalen: 1460
Callback: Recieved VMA packet 0x7f5787df1bb0 containing data of length: 8760, Total data recieved until now: 32120
recvfrom_zcopy: Packet_id: 0x7f5787df1bb0 datalen: 8760
Callback: Recieved VMA packet 0x7f5787df2240 containing data of length: 1460, Total data recieved until now: 33580
recvfrom_zcopy: Packet_id: 0x7f5787df2240 datalen: 1460
Callback: Recieved VMA packet 0x7f5787df2358 containing data of length: 7300, Total data recieved until now: 40880
recvfrom_zcopy: Packet_id: 0x7f5787df2358 datalen: 4461
recvfrom_zcopy: Packet_id: 0x7f5787df28d0 datalen: 4541
```

Client logs:
```c
dce@alba154232:~/vikram$ export LD_PRELOAD=/usr/lib64/libvma.so; ./client_vma 192.168.1.1 8000 4096 10 100
 VMA INFO: ---------------------------------------------------------------------------
 VMA INFO: VMA_VERSION: 7.0.14-0 Release built on Jan 28 2016 20:41:00
 VMA INFO: Cmd Line: ./client_vma 192.168.1.1 8000 4096 10 100
 VMA INFO: OFED Version: MLNX_OFED_LINUX-3.2-1.0.1.1:
 VMA INFO: Log Level                      INFO                       [VMA_TRACELEVEL]
 VMA INFO: ---------------------------------------------------------------------------
Buf[0] sent (Total data sent: 4096)
Buf[1] sent (Total data sent: 8192)
Buf[2] sent (Total data sent: 12288)
Buf[3] sent (Total data sent: 16384)
Buf[4] sent (Total data sent: 20480)
Buf[5] sent (Total data sent: 24576)
Buf[6] sent (Total data sent: 28672)
Buf[7] sent (Total data sent: 32768)
Buf[8] sent (Total data sent: 36864)
Buf[9] sent (Total data sent: 40960)
##Overall Total data sent = 40960 bytes
```

Issue:

* Total data sent by client is 40960 bytes, while server received less than this i.e. 40880 bytes. So it looks to be data loss. You can also look at the code attached, to see if anything missing w.r.t API usage.

* From the logs you can see that, for the last packet the amount of data reported by the server_vma_recv_callback and recvfrom_zcopy are different for same packet. And also for packet (0x7f5787df2358) callback is not invoked but recvfrom_zopy event recieved.

```c
Callback: Recieved VMA packet 0x7f5787df2358 containing data of length: 7300, Total data recieved until now: 40880
recvfrom_zcopy: Packet_id: 0x7f5787df2358 datalen: 4461
```

We are blocked on this, so an early resolution to this would be very helpful.

**Comment by vikramsc** [comment]
Following zip file contains the source code & vma_stats log file.

[vma_callback.tar.gz](https://github.com/Mellanox/libvma/files/141921/vma_callback.tar.gz)

**Comment by rosenbaumalex** [comment]
we'll need to take a closer look at this. we'll get back soon.
please update if you find anything on your side.

**Comment by mtami** [comment]
Hi,
the attached files missing file called : server_vma_zcopy.c 
we need it to compile your program.
can you please attach it and resend the compressed file.

**Comment by vikramsc** [comment]
Hi,

Attached the tar.gz below containing code:

[vma_callback.tar.gz](https://github.com/Mellanox/libvma/files/158121/vma_callback.tar.gz)

Thanks & Regards,
Vikram

**Comment by mtami** [comment]
Hi,
when i am trying to compile the program with make, it returns with an Error:
make: *** No rule to make target `server_vma_zcopy.c', needed by `server_vma_zcopy'.  Stop.

the file  server_vma_zcopy.c needed to compile program correctly.
please send this file to be able compiling the program and investigating the issue.

Best Regards,
Tamie

**Comment by vikramsc** [comment]
Hi,

Very sorry for that. Attaching the tar containing all the files.

[vma_callback.tar.gz](https://github.com/Mellanox/libvma/files/160704/vma_callback.tar.gz)

Thanks & Regards,
Vikram

**Comment by mtami** [comment]
Thanks,

**Comment by OphirMunk** [comment]
Vikramsc,
Please let know if the fix of issue [#43](https://github.com/Mellanox/libvma/issues/43) has any effect in this case as well. Please note you will have to fix your server_vma_cb.c file and advance in user buffer as exemplified in server_vma.c in issue [#43](https://github.com/Mellanox/libvma/issues/43)

**Comment by OphirMunk** [comment]
Vikramsc - any updates?

**Comment by vikramsc** [comment]
Hi OphirMunk,

I ran the test again with the libvma.so containing fix https://github.com/Mellanox/libvma/issues/43 and this issue is not seen. So closing this.

Thanks,
Vikram

**Comment by OphirMunk** [comment]
Hi Vikramsc,
Thanks for the update. Good news.
Regards,
Ophir
