### ISSUE TITLE
VMA ring allocation problem

### ISSUE THREAD

**Issue by sm1ly** [Mellanox/libvma#48]
Hello team.

I have some issue with VMA VMA_RING_ALLOCATION_LOGIC_RX=30.
My application is a client application, which listens to UDP multicast. If I use VMA_RING_ALLOCATION_LOGIC_RX=30 I have some measurable decrease in latency, but on the other side my application starts to lose packets.

I managed to fix it in 2 ways: 1. pin my application to 1 core. 2. Set VMA_RING_MIGRATION_RATIO_RX = -1. I have noticed that the application loses packets when the most loaded CPU core changes on another one. And I guess the packets loss during RING migration.

Is it the correct behavior of VMA or not?

**Comment by liranoz12** [comment]
@sm1ly,

Yes, this is the expected behavior.
Please consider using VMA_RING_ALLOCATION_LOGIC_RX=31 which attaches each thread to a cpu core.

**I guess the packets loss during RING migration.**
Correct. You can also monitor migration operations using vma statistics tool.

Thanks,
Liran
