### ISSUE TITLE
Errors building libvma on Ubuntu 16.04

### ISSUE THREAD

**Issue by haggaie** [Mellanox/libvma#544]
I'm trying to build a dpkg for Ubuntu 16.04 using the `build/build_deb.sh` script, and I came across an error:

    In file included from ../../src/vma/event/event_handler_manager.h:41:0,
                     from stats_publisher.cpp:41:
    ../../src/vma/netlink/netlink_wrapper.h:38:29: fatal error: netlink/netlink.h: No such file or directory

It seems like on Ubuntu 16.04, libibverbs isn't linked against libnl3 or libnl-3, so the `nl.m4` script determines `HAVE_LIBNL` is false, and doesn't set `LIBNL_CFLAGS`. However, the build still tries to build code that relies on the netlink header files.

What would be the right way to solve this? Should libvma require a version of libnl, or is this dependency should be qualified under a check for `HAVE_LIBNL`?

**Comment by rafiw** [comment]
@haggaie vma must use the same libnl as libibverbs uses
please supply output of
ldd libibverbs.so on that machine
also need to verify that the nl.m4 has the right path to the so file
config.log can help

**Comment by haggaie** [comment]
Here's the version of libibverbs I have:

    # dpkg -s libibverbs-dev | grep Version
    Version: 1.1.8-1.1ubuntu2

And the output of `ldd`:

    # ldd /usr/lib/libibverbs.so
            linux-vdso.so.1 =>  (0x00007fff83df0000)
            libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fee30440000)
            libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fee3023c000)
            libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fee2fe71000)
            /lib64/ld-linux-x86-64.so.2 (0x00007fee30873000)

I didn't see any relevant output in `config.log`. It skips from pthread check (before the CHECK_NL_LIB() call) right to atomic memory access:

    configure:18455: checking for pthread_create in -lpthread
    configure:18480: gcc -o conftest -g -D_GNU_SOURCE -fPIC -g -O2 -Wall -Wextra -Werror -Wundef -ffunction-sections -fdata-sections -Wsequence-point -pipe -Winit-self -Wmissing-include-dirs -O3  -I/usr/include  -L/usr/lib conftest.c -lpthread  -lrt -ldl -lstdc++  >&5
    configure:18480: $? = 0
    configure:18489: result: yes
    configure:18699: checking for atomic memory access (__sync_bool_compare_and_swap) support
    configure:18716: gcc -o conftest -g -D_GNU_SOURCE -fPIC -g -O2 -Wall -Wextra -Werror -Wundef -ffunction-sections -fdata-sections -Wsequence-point -pipe -Winit-self -Wmissing-include-dirs -O3  -I/usr/include  -L/usr/lib conftest.c -lpthread -lrt -ldl -lstdc++  >&5
    configure:18716: $? = 0
    configure:18718: result: yes

However, it does show that `ac_cv_ofed_path=/usr`, so it should find the right so file.

**Comment by rafiw** [comment]
#546 should fix the issue

**Comment by liranoz12** [comment]
Hi,
Issue should be solved as part of #546.
Thanks for your feedback.
Liran
