### ISSUE TITLE
MPRQ: randomly receiving multicast streams

### ISSUE THREAD

**Issue by eloi29** [Mellanox/libvma#594]
Hi,
I am using on MPRQ to receive multicast streams.

Randomly, I never receive my multicast packets (2 streams) but can see them on tcpdump.
It looks like completion packets are equal to zero. I follow your example in the VMA documentation.
See in attachment VMA logs.[mprq.log](https://github.com/Mellanox/libvma/files/1811763/mprq.log)

When VMA do receive it, I notice poor performance compared to other solutions such as recvfrom_zcopy or libvma vanilla

Any ideas ?

Thanks,

**Comment by rafiw** [comment]
Hi @eloi29 
how much BW is used per stream?
you are using a lot of memory, try using much less use 1<<17 as num value
what packet size are you receiving? 
is it the same size for all packets?
does it happen with one stream?

**Comment by NirNitzani** [comment]
Hi @eloi29

In order to get further support please contact me directly nirni@mellanox.com

Thanks
Nir

**Comment by eloi29** [comment]
Hi,
My setup is actually quite simple.

* one multicast stream of 1.5 gbps
* the packet size is 1220 or 820 bytes depending on the packet so the size alternates
* I also increased the ring size and tried different value for min and max of vma_cyclic_buffer_read

I see 2 issues ATM:

* incoming streams sometimes no handled by VMA. I would say it occurs 1/3 times
* poor performances comparing to recvfrom zcopy or libvma vanilla.

I will post that also to nirni@mellanox.com

Thanks
