### ISSUE TITLE
Running ping with libvma using dns name resolving does not work.

### ISSUE THREAD

**Issue by vbreugel** [Mellanox/libvma#60]
When I run the command ping with the libvma option with a hostname, result comes back with unknown hostname while the host is resolvable.

Running the ping command IP based, no problems.

Can libvma handle DNS resolution with HW offload or do you always have to use the OS redirect for this?

**Comment by rosenbaumalex** [comment]
Fixed in commit https://github.com/Mellanox/libvma/commit/d487cf52304889feee4b73c7b681e5c6c3b848ad

**Comment by rosenbaumalex** [comment]
Will be part of VMA 8.1.1 tag 
closing issue
