### ISSUE TITLE
epoll_wait() can't be interrupted with VMA_SELECT_POLL=-1

### ISSUE THREAD

**Issue by andl** [Mellanox/libvma#719]
Hi,

I create a simple epoll-test application to test libvma on my system. The environment is
- libvma v8.7.0 which is bundled in mlnx-ofed 4.4-2 driver.
- CentOS 7, 64bit. 
- gcc 4.8

the full source code can be found at: https://gist.github.com/andl/f16015de477b75297aab4502886a4e46, while the idea is evoke epoll_wait on listen socket and wait indefinitely for incoming connection, unless get interrupted. 

```c
// create a listen socket and add to epoll
nfds = epoll_wait(epoll_fd, events, MAX_EVENTS, -1);
if (nfds == -1) {
    if (errno == EINTR) {
            printf("epoll_wait interrupted\n"); 
            close(listen_sock);
            exit(0);
    }
}
```
build using `gcc -o epoll-test ./epoll-test.c` and run without libvma or using vma default parameter. Press Ctrl-C can interrupt epoll_wait() as expected.
```
$ ./epoll-test 
^Con SIGINT
epoll_wait interrupted
$ LD_PRELOAD=libvma.so ./epoll-test
 VMA INFO: ---------------------------------------------------------------------------
 VMA INFO: VMA_VERSION: 8.7.0-0 Release built on Aug  9 2018 12:21:50
 VMA INFO: Cmd Line: ./epoll-test
 VMA INFO: OFED Version: MLNX_OFED_LINUX-4.4-2.0.7.0:
 VMA INFO: ---------------------------------------------------------------------------
 VMA INFO: Log Level                      INFO                       [VMA_TRACELEVEL]
 VMA INFO: ---------------------------------------------------------------------------

^Con SIGINT
epoll_wait interrupted
```
But if I start test app using either of the following parameters, epoll_wait() can't be interrupted using CTRL-C from indefinitely wait. 
```
$ VMA_SPEC=latency LD_PRELOAD=libvma.so ./epoll-test
$ VMA_SELECT_POLL=-1 LD_PRELOAD=libvma.so ./epoll-test
$ VMA_SELECT_POLL=-1 VMA_HANDLE_SIGINTR=1 LD_PRELOAD=libvma.so ./epoll-test
```
Is this a bug of vma or by-design behavior?

**Comment by liranoz12** [comment]
Hi @andl ,

It looks like a bug. i will provide a fix soon.
Thanks for reporting.

Liran

**Comment by andl** [comment]
Hi @liranoz12, just wondering do you guys have a ETA to fix this annoying bug?

**Comment by liranoz12** [comment]
@andl,

The fix for this issue will be included in the next official release.
Could you please provide more information about your application/VMA usage ?

Thanks,

**Comment by andl** [comment]
> @andl,
> 
> The fix for this issue will be included in the next official release.
good to know, thanks a lot. 
> Could you please provide more information about your application/VMA usage ?
my app logic is simple, it's single thread and the main loop evoke `epoll_wait`with indefinitely timeout. On the other hand, it has to be able to response to signal like USR1/HUP. Since linux native `epoll_wait` can be interrupted, this is not an issue when I run without libvma. While like the demo code posted in the bug report, running my app with `VMA_SELECT_POLL=-1` break this behavior. 
> 
> Thanks,

**Comment by liranoz12** [comment]
@andl,

Fix was merged to the master brunch.
Please see 6e2f046b9b6ab0e7add85b13f7fe4cf675c93d9b.
Thanks for reporting,
Liran
