### ISSUE TITLE
add_conf_rule function signature unclear

### ISSUE THREAD

**Issue by danfruehauf** [Mellanox/libvma#742]
The function `add_conf_rule` has the following signature:
```
int (*add_conf_rule)(char *config_line);
```

I think a more correct signature should be:
```
int (*add_conf_rule)(const char *config_line);
```

And if the string needs to turn into a buffer, it is probably more correct to have it happen behind the scenes, so simple usage like the following can take place:
```
vma_api->add_conf_rule("...");
```
At the moment, this would yield:
```
warning: ISO C++ forbids converting a string constant to ‘char*’ [-Wwrite-strings]
   vma_api->add_conf_rule("...");
```

**Comment by liranoz12** [comment]
@danfruehauf, Thanks for your feedback.
We will fix that as part of the next release.

Thanks,
Liran

**Comment by liranoz12** [comment]
@danfruehauf,

The fix was merged to the master brunch.
Thanks again for your report.

Liran
