### ISSUE TITLE
error: create more than 1024 sockets 

### ISSUE THREAD

**Issue by CCrainys** [Mellanox/libvma#803]
I encountered a problem when I test libvma performance through memcached. 
According to guideline from https://community.mellanox.com/s/article/vma-improves-memcached-performance-over-10gbe-networks , I started my test on memcached and vma. Memslap is a tool which is used to test memcached performance. I use memslap to create 6k connections concurrently from client to memcached server. If I use tcp protocol, the memslap works successfully. However, I found that If I use vma protocol, It failed to create 6k connection."

The command I run in client:
      VMA_RING_ALLOCATION_LOGIC_TX=20 VMA_RING_ALLOCATION_LOGIC_RX=20 LD_PRELOAD=libvma.so taskset -c 8-15 memaslap -s 63.63.63.82:11211 -T 8 -c 6400 -t 30s -X 64 -S 1s

The command I run in memcached server:
      LD_PRELOAD=libvma.so VMA_RING_ALLOCATION_LOGIC_TX=31 VMA_RING_ALLOCATION_LOGIC_RX=31  taskset -c 8-15 memcached -m 12000 -l 63.63.63.82 -u root -t 7 -c 10000

The error information in memslap client:
![image](https://user-images.githubusercontent.com/18700694/51814611-24223980-22f7-11e9-9359-733412efc4ec.png)

The error information in memcached server:
![image](https://user-images.githubusercontent.com/18700694/51814621-31d7bf00-22f7-11e9-8171-b7e2829b2fd7.png)

**Comment by liranoz12** [comment]
Hi,

it seems like you have exceeded the maximum amount of open file descriptors for process.
VMA opens additional epoll fd for each socket (used by the wakeup mechanism). Hence, there are no issues while VMA is not used.
You can verify this amount using:
`ls -l /proc/<PID>/fd | wc -l`

Thanks for reporting,
Liran

**Comment by CCrainys** [comment]
Hi,
So you mean that VMA couldn't support massive connections.
Actually, the error info shows that vma can only monitor 1024 sockets, so I
read some source code of vma.
In VMA source code,  I find:
      1.  MAX_STATS_FD_NUM=1024
      2. In
https://github.com/Mellanox/libvma/blob/master/src/vma/sock/sock-redirect.h
,

[image: Screen Shot 2019-01-30 at 12.21.22 AM.png]
There are a lot of restrictions in VMA which restrict vma ability to handle
massive connections.

From my point of my view, vma can only support 1024 sockets. If I want to
make vma support massive connections, I have to modify source code by
myself. (I try some simple modifications to code, let vma succeed working
in 2k concurrent connections .)

Is my understanding correct? Or I can make the vma support massive
connections by simply setting some parameters? If so, please tell me how to
do it?


Liran Oz <notifications@github.com> 于2019年1月29日周二 下午9:10写道：

**Comment by CCrainys** [comment]
Hi,
So you mean that VMA couldn't support massive connections.
Actually, the error info shows that vma can only monitor 1024 sockets, so I read some source code of vma.

In VMA source code,  I find:
     1.  MAX_STATS_FD_NUM=1024
     2. In https://github.com/Mellanox/libvma/blob/master/src/vma/sock/sock-redirect.h
<img width="506" alt="screen shot 2019-01-30 at 12 21 22 am" src="https://user-images.githubusercontent.com/18700694/51924269-aa3d9d80-2427-11e9-9aaf-8b43eefeca05.png">


There are a lot of restrictions in VMA which restrict vma ability to handle massive connections. 

From my point of my view, vma can only support 1024 sockets. If I want to make vma support massive connections, I have to modify source code by myself. (I try some simple modifications to code, let vma succeed working in 2k concurrent connections .)
 
Is my understanding correct? Or I can make the vma support massive connections by simply setting some parameters? If so, please tell me how to do it?

Thanks

**Comment by liranoz12** [comment]
Hi,

No this is not what i meant. i will try to clarify my explanation:

1. VMA should support 6k TCP connections without issues. In fact, we are testing such amount of connection daily.
2. [VMA_STATS_FD_NUM](https://github.com/Mellanox/libvma/blob/master/README.txt#L324:L327) Warning/parameter - This is the max number of sockets monitored by VMA statistic mechanism. this is not related to the amount of supported sockets at all.
For vma statistics tool usage please refer to [VMA user manual](http://www.mellanox.com/page/software_vma?mtag=vma). 
3. SELECT_BIG_SETSIZE - This limitation is related only to select()/pselect() calls. i am not familiar with memcached implementation. But from a quick look it seems like select()/pselect() are not used by memcached at all so the limitation is not related to your issue.
Anyway, select API is not reccomened to use with large amount of sockets - please see the following [article](http://devarea.com/linux-io-multiplexing-select-vs-poll-vs-epoll/). : 

```
Epoll vs Select/Poll
epoll has better performance – O(1) instead of O(n)
```

4. Please try to increase the amount of supported FDs for a process and rerun your application (not a VMA parameter).
As far as i remember _ulimit -Hn 15000_ should help but i dont sure about it.

Thanks,
Liran

**Comment by CCrainys** [comment]
Hi, Liran

Before I created issue in github, I had already executed command : ulimit -n 20000.
Unfortunately,  It didn't work.

Thanks for your detailed explanation. I understand what you mean. I will try some other ways to increase the amount of FD support by a process.

Thanks & Regards,
Jimmy

**Comment by CCrainys** [comment]
Hi, Liran

Thanks for your patience and quick response.

You said vma can support 6k connections in your daily testing. Can you provide a specific demo and detailed procedures to reproduce experiment results? 

Please forgive me if I have caused you any trouble.

Thanks & Regards,
Jimmy

**Comment by liranoz12** [comment]
Hi,

We are using Sockperf for those tests - see feed file, command and output below.
The following example creates 6k tcp sockets in the client and 12k sockets in the server (6k listen + 6k established, equals to total amount of 24023 open file descriptors).

[6000s_tcp_a.txt](https://github.com/Mellanox/libvma/files/2816883/6000s_tcp_a.txt)

**Server :** 
[lirano@r-aa-apollo03 libvma]$ VMA_SPEC=latency LD_PRELOAD=libvma.so  taskset -c 2 sockperf sr -f ./feed_files/6000s_tcp_a.txt
 VMA INFO: ---------------------------------------------------------------------------
 VMA INFO: VMA_VERSION: 8.7.7-0 Development Snapshot built on Jan 30 2019 15:59:38
 VMA INFO: Git: 3e67b77b994154caf6ca30a73762038edfaed3ec
 VMA INFO: Cmd Line: sockperf sr -f ./feed_files/6000s_tcp_a.txt
 VMA INFO: Current Time: Thu Jan 31 11:04:24 2019
 VMA INFO: Pid: 15071
 VMA INFO: OFED Version: MLNX_OFED_LINUX-4.5-1.0.1.0:
 VMA INFO: Architecture: x86_64
 VMA INFO: Node: r-aa-apollo03.mtr.labs.mlnx
 VMA INFO: ---------------------------------------------------------------------------
 VMA INFO: VMA Spec                       Latency                    [VMA_SPEC]
 VMA INFO: Log Level                      INFO                       [VMA_TRACELEVEL]
 VMA INFO: Ring On Device Memory TX       16384                      [VMA_RING_DEV_MEM_TX]
 VMA INFO: Tx QP WRE                      256                        [VMA_TX_WRE]
 VMA INFO: Tx QP WRE Batching             4                          [VMA_TX_WRE_BATCHING]
 VMA INFO: Rx QP WRE                      256                        [VMA_RX_WRE]
 VMA INFO: Rx QP WRE Batching             4                          [VMA_RX_WRE_BATCHING]
 VMA INFO: Rx Poll Loops                  -1                         [VMA_RX_POLL]
 VMA INFO: Rx Prefetch Bytes Before Poll  256                        [VMA_RX_PREFETCH_BYTES_BEFORE_POLL]
 VMA INFO: GRO max streams                0                          [VMA_GRO_STREAMS_MAX]
 VMA INFO: Select Poll (usec)             -1                         [VMA_SELECT_POLL]
 VMA INFO: Select Poll OS Force           Enabled                    [VMA_SELECT_POLL_OS_FORCE]
 VMA INFO: Select Poll OS Ratio           1                          [VMA_SELECT_POLL_OS_RATIO]
 VMA INFO: Select Skip OS                 1                          [VMA_SELECT_SKIP_OS]
 VMA INFO: CQ Drain Interval (msec)       100                        [VMA_PROGRESS_ENGINE_INTERVAL]
 VMA INFO: CQ Interrupts Moderation       Disabled                   [VMA_CQ_MODERATION_ENABLE]
 VMA INFO: CQ AIM Max Count               128                        [VMA_CQ_AIM_MAX_COUNT]
 VMA INFO: CQ Adaptive Moderation         Disabled                   [VMA_CQ_AIM_INTERVAL_MSEC]
 VMA INFO: CQ Keeps QP Full               Disabled                   [VMA_CQ_KEEP_QP_FULL]
 VMA INFO: TCP nodelay                    1                          [VMA_TCP_NODELAY]
 VMA INFO: Avoid sys-calls on tcp fd      Enabled                    [VMA_AVOID_SYS_CALLS_ON_TCP_FD]
 VMA INFO: Internal Thread Affinity       0                          [VMA_INTERNAL_THREAD_AFFINITY]
 VMA INFO: Thread mode                    Single                     [VMA_THREAD_MODE]
 VMA INFO: Mem Allocate type              2 (Huge Pages)             [VMA_MEM_ALLOC_TYPE]
 VMA INFO: ---------------------------------------------------------------------------
 VMA INFO: VMA Statistics can monitor up to 100 sockets - increase VMA_STATS_FD_NUM
sockperf: == version #3.6-no.git ==
sockperf: [SERVER] listen on:
[0] IP = 22.0.0.3        PORT = 10666 # TCP
[1] IP = 22.0.0.3        PORT = 10667 # TCP
[2] IP = 22.0.0.3        PORT = 10668 # TCP
[3] IP = 22.0.0.3        PORT = 10669 # TCP
[4] IP = 22.0.0.3        PORT = 10670 # TCP
[5] IP = 22.0.0.3        PORT = 10671 # TCP
....
....
....
....
[5996] IP = 22.0.0.3        PORT = 16662 # TCP
[5997] IP = 22.0.0.3        PORT = 16663 # TCP
[5998] IP = 22.0.0.3        PORT = 16664 # TCP
[5999] IP = 22.0.0.3        PORT = 16665 # TCP
sockperf: Warmup stage (sending a few dummy messages)...
sockperf: [tid 15071] using epoll() to block on socket(s)

**Client:**
[lirano@r-aa-apollo04 libvma]$ VMA_SPEC=latency LD_PRELOAD=./libvma.so  taskset -c 2 sockperf pp -f ./feed_files/6000s_tcp_a.txt -t 5
 VMA INFO: ---------------------------------------------------------------------------
 VMA INFO: VMA_VERSION: 8.7.7-0 Development Snapshot built on Jan 30 2019 15:59:38
 VMA INFO: Git: 3e67b77b994154caf6ca30a73762038edfaed3ec
 VMA INFO: Cmd Line: sockperf pp -f ./feed_files/6000s_tcp_a.txt -t 5
 VMA INFO: Current Time: Thu Jan 31 11:12:04 2019
 VMA INFO: Pid:  6920
 VMA INFO: OFED Version: MLNX_OFED_LINUX-4.5-1.0.1.0:
 VMA INFO: Architecture: x86_64
 VMA INFO: Node: r-aa-apollo04.mtr.labs.mlnx
 VMA INFO: ---------------------------------------------------------------------------
 VMA INFO: VMA Spec                       Latency                    [VMA_SPEC]
 VMA INFO: Log Level                      INFO                       [VMA_TRACELEVEL]
 VMA INFO: Ring On Device Memory TX       16384                      [VMA_RING_DEV_MEM_TX]
 VMA INFO: Tx QP WRE                      256                        [VMA_TX_WRE]
 VMA INFO: Tx QP WRE Batching             4                          [VMA_TX_WRE_BATCHING]
 VMA INFO: Rx QP WRE                      256                        [VMA_RX_WRE]
 VMA INFO: Rx QP WRE Batching             4                          [VMA_RX_WRE_BATCHING]
 VMA INFO: Rx Poll Loops                  -1                         [VMA_RX_POLL]
 VMA INFO: Rx Prefetch Bytes Before Poll  256                        [VMA_RX_PREFETCH_BYTES_BEFORE_POLL]
 VMA INFO: GRO max streams                0                          [VMA_GRO_STREAMS_MAX]
 VMA INFO: Select Poll (usec)             -1                         [VMA_SELECT_POLL]
 VMA INFO: Select Poll OS Force           Enabled                    [VMA_SELECT_POLL_OS_FORCE]
 VMA INFO: Select Poll OS Ratio           1                          [VMA_SELECT_POLL_OS_RATIO]
 VMA INFO: Select Skip OS                 1                          [VMA_SELECT_SKIP_OS]
 VMA INFO: CQ Drain Interval (msec)       100                        [VMA_PROGRESS_ENGINE_INTERVAL]
 VMA INFO: CQ Interrupts Moderation       Disabled                   [VMA_CQ_MODERATION_ENABLE]
 VMA INFO: CQ AIM Max Count               128                        [VMA_CQ_AIM_MAX_COUNT]
 VMA INFO: CQ Adaptive Moderation         Disabled                   [VMA_CQ_AIM_INTERVAL_MSEC]
 VMA INFO: CQ Keeps QP Full               Disabled                   [VMA_CQ_KEEP_QP_FULL]
 VMA INFO: TCP nodelay                    1                          [VMA_TCP_NODELAY]
 VMA INFO: Avoid sys-calls on tcp fd      Enabled                    [VMA_AVOID_SYS_CALLS_ON_TCP_FD]
 VMA INFO: Internal Thread Affinity       0                          [VMA_INTERNAL_THREAD_AFFINITY]
 VMA INFO: Thread mode                    Single                     [VMA_THREAD_MODE]
 VMA INFO: Mem Allocate type              2 (Huge Pages)             [VMA_MEM_ALLOC_TYPE]
 VMA INFO: ---------------------------------------------------------------------------
 VMA INFO: VMA Statistics can monitor up to 100 sockets - increase VMA_STATS_FD_NUM
sockperf: == version #3.6-no.git ==
sockperf[CLIENT] send on:sockperf: using epoll() to block on socket(s)
[0] IP = 22.0.0.3        PORT = 10666 # TCP
[1] IP = 22.0.0.3        PORT = 10667 # TCP
[2] IP = 22.0.0.3        PORT = 10668 # TCP
[3] IP = 22.0.0.3        PORT = 10669 # TCP
[4] IP = 22.0.0.3        PORT = 10670 # TCP
[5] IP = 22.0.0.3        PORT = 10671 # TCP
....
....
....
....
[5995] IP = 22.0.0.3        PORT = 16661 # TCP
[5996] IP = 22.0.0.3        PORT = 16662 # TCP
[5997] IP = 22.0.0.3        PORT = 16663 # TCP
[5998] IP = 22.0.0.3        PORT = 16664 # TCP
[5999] IP = 22.0.0.3        PORT = 16665 # TCP
sockperf: Warmup stage (sending a few dummy messages)...
sockperf: Starting test...
sockperf: Test end (interrupted by timer)
sockperf: Test ended
sockperf: [Total Run] RunTime=5.001 sec; Warm up time=650 msec; SentMessages=843215; ReceivedMessages=843214
sockperf: ========= Printing statistics for Server No: 0
sockperf: [Valid Duration] RunTime=4.551 sec; SentMessages=767153; ReceivedMessages=767153
sockperf: ====> avg-latency=2.948 (std-dev=0.613)
sockperf: # dropped messages = 0; # duplicated messages = 0; # out-of-order messages = 0
sockperf: Summary: Latency is 2.948 usec
sockperf: Total 767153 observations; each percentile contains 7671.53 observations
sockperf: ---> <MAX> observation =   17.800
sockperf: ---> percentile 99.999 =   11.085
sockperf: ---> percentile 99.990 =   10.837
sockperf: ---> percentile 99.900 =   10.535
sockperf: ---> percentile 99.000 =    5.048
sockperf: ---> percentile 90.000 =    3.330
sockperf: ---> percentile 75.000 =    3.094
sockperf: ---> percentile 50.000 =    2.852
sockperf: ---> percentile 25.000 =    2.674
sockperf: ---> <MIN> observation =    2.302

Thanks,
Liran

**Comment by CCrainys** [comment]
Hi, Liran

Thanks for your help, I'll test it in my own machines.

Best Regards
Jimmy
