### ISSUE TITLE
Socket fd or poll fd as parametr of socketxtreme_poll()

### ISSUE THREAD

**Issue by eXXXtrema1** [Mellanox/libvma#822]
Currently, socketxtreme_poll() cannot accept a socket descriptor or poll descriptor as a parameter.
For example this code not work correctly:
```
int fd = socket(AF_INET, SOCK_DGRAM, IPPROTO_UDP);
// binding socket...
vma_api->socketxtreme_poll(fd , &vma_comps, 1, 0);
```

but this code work's properly:
```
int fd = socket(AF_INET, SOCK_DGRAM, IPPROTO_UDP);
// binding socket...
vma_api->get_socket_rings_fds(fd , &_vma_ring_fd, 1);
vma_api->socketxtreme_poll(_vma_ring_fd, &vma_comps, 1, 0);
```
Why so ?

From documentation:
> The `fd` can represent a ring, socket or epoll file descriptor

**Comment by liranoz12** [comment]
Hi @eXXXtrema1,

This is a mistake in the documentation, The only valid option to use socketXtreme_poll is to specify the ring file descriptor.
We will fix our documentation accordingly.

Thanks,

**Comment by eXXXtrema1** [comment]
Hi, @liranoz12 !

Please tell me the fastest way to receive data from 4 UDP connections in one thread. The latency is very critical. I planned to use socketxtreme_poll with epoll file descriptor for this purpose, but it will not work.

Thanks.

**Comment by igor-ivanov** [comment]
Hi @eXXXtrema1, you can use socketXtreme for this. You can study following applications that use socketXtreme/UDP as https://github.com/Mellanox/libvma/blob/master/tests/testbed/testbed.c or https://github.com/mellanox/sockperf
