### ISSUE TITLE
vma_cyclic_buffer_read fails in OFED 4.6

### ISSUE THREAD

**Issue by spencerjs** [Mellanox/libvma#858]
With OFED 4.6 on RHEL 7.5, calls to vma_cyclic_buffer_read fail.  Either calls fail, or the data returned is not valid.  When data is returned, 46 bytes of header are seen instead of the 42 specified in the PADDED_PACKET option.

**Comment by NirNitzani** [comment]
Hi Spencer,

we have addressed this issue - see VMA version 8.9.4 it should be fixed.
as a general note - this is a beta quality feature that is based on experimental verbs that will be deprecated in the next release.
A similar optimized feature and much more is supported as part of our Rivermax SW SDK.

Thank you for highlighting the issue -
Nir Nitzani
