### ISSUE TITLE
Higher latency in recent VMA versions.

### ISSUE THREAD

**Issue by spencerjs** [Mellanox/libvma#860]
We’ve successfully used MPRQ within VMA since it was added to OFED.  In recent versions (> 4.3.X) we’ve observed latency issues using the MPRQ APIs to receive multicast streams within our application.  Our application receives bursts of multicast packets over 100 GbE using ConnectX5 adapters.    

   Using the same software and changing only the OFED version from 4.3.X to 4.4.X or greater will cause the measured latency to increase  by approximate 2 ms.  This latency is measured using TSC registers within the processor.

   4.2.X = ~2.8 ms latency
   4.3.X = ~2.8 ms latency
   4.4.X = ~4.7 ms latency
   4.5.X = ~4.7 ms latency
   4.6.X  = Does not function (see issue 858)

**Comment by NirNitzani** [comment]
Hi Spencer,

we believe that this issue has been addressed this issue - see VMA version 8.9.4 - part of OFED 4.7
as a general note - this is a beta quality feature that is based on experimental verbs that will be deprecated in the next release.
A similar optimized feature and much more is supported as part of our Rivermax SW SDK.

Thank you for highlighting the issue -
Nir Nitzani
