### ISSUE TITLE
LibVMA shows the same performance with Linux socket on Centos 7.6.

### ISSUE THREAD

**Issue by Uanenang** [Mellanox/libvma#889]
Hi, I got the same throughput and latency with the Linux TCP socket. It seems like the traffic hasn't been offloaded.  I tried to use vma_stats to monitor traffic and it showed nothing. 

I am using the following setting.
$ ofed_info -s
MLNX_OFED_LINUX-4.7-1.0.0.1:

$ sudo mst status -vv
PCI devices:
DEVICE_TYPE             MST      PCI       RDMA            NET                       NUMA
ConnectX4(rev:0)        NA       03:00.0   mlx5_0          net-p6p1                  0

$ ibdev2netdev
mlx4_0 port 1 ==> p5p1 (Down)
mlx4_0 port 2 ==> p5p2 (Down)
**mlx5_0 port 1 ==> p6p1 (Up)**
mlx5_1 port 1 ==> p7p1 (Up)

**Output Message.**

1. Libvma.
Server side.
> $ VMA_RX_UDP_POLL_OS_RATIO=0  VMA_SELECT_POLL_OS_RATIO=0 LD_PRELOAD=libvma.so numactl --cpunodebind=0 taskset -c 0,2 sockperf sr --msg-size 64 --ip 10.1.3.45 --port 19140 --tcp
 VMA INFO: ---------------------------------------------------------------------------
 VMA INFO: VMA_VERSION: 9.0.2-0 Development Snapshot built on Feb 24 2020 20:57:59
 VMA INFO: Git: 1585579238d56e917e650e5381b34a8aaaeca149
 VMA INFO: Cmd Line: numactl --cpunodebind=0 taskset -c 0,2 sockperf sr --msg-size 64 --ip 10.1.3.45 --port 19140 --tcp
 VMA INFO: Current Time: Mon Mar 23 10:55:10 2020
 VMA INFO: Pid: 17100
 VMA INFO: OFED Version: MLNX_OFED_LINUX-4.7-1.0.0.1:
 VMA INFO: Architecture: x86_64
 VMA INFO: Node: NETSYS45
 VMA INFO: ---------------------------------------------------------------------------
 VMA INFO: Log Level                      INFO                       [VMA_TRACELEVEL]
 VMA INFO: Rx UDP Poll OS Ratio           Disabled                   [VMA_RX_UDP_POLL_OS_RATIO]
 VMA INFO: Select Poll OS Ratio           Disabled                   [VMA_SELECT_POLL_OS_RATIO]
 VMA INFO: ---------------------------------------------------------------------------
 VMA INFO: ---------------------------------------------------------------------------
 VMA INFO: VMA_VERSION: 9.0.2-0 Development Snapshot built on Feb 24 2020 20:57:59
 VMA INFO: Git: 1585579238d56e917e650e5381b34a8aaaeca149
 VMA INFO: Cmd Line: taskset -c 0,2 sockperf sr --msg-size 64 --ip 10.1.3.45 --port 19140 --tcp
 VMA INFO: Current Time: Mon Mar 23 10:55:10 2020
 VMA INFO: Pid: 17100
 VMA INFO: OFED Version: MLNX_OFED_LINUX-4.7-1.0.0.1:
 VMA INFO: Architecture: x86_64
 VMA INFO: Node: NETSYS45
 VMA INFO: ---------------------------------------------------------------------------
 VMA INFO: Log Level                      INFO                       [VMA_TRACELEVEL]
 VMA INFO: Rx UDP Poll OS Ratio           Disabled                   [VMA_RX_UDP_POLL_OS_RATIO]
 VMA INFO: Select Poll OS Ratio           Disabled                   [VMA_SELECT_POLL_OS_RATIO]
 VMA INFO: ---------------------------------------------------------------------------
 VMA INFO: ---------------------------------------------------------------------------
 VMA INFO: VMA_VERSION: 9.0.2-0 Development Snapshot built on Feb 24 2020 20:57:59
 VMA INFO: Git: 1585579238d56e917e650e5381b34a8aaaeca149
 VMA INFO: Cmd Line: sockperf sr --msg-size 64 --ip 10.1.3.45 --port 19140 --tcp
 VMA INFO: Current Time: Mon Mar 23 10:55:10 2020
 VMA INFO: Pid: 17100
 VMA INFO: OFED Version: MLNX_OFED_LINUX-4.7-1.0.0.1:
 VMA INFO: Architecture: x86_64
 VMA INFO: Node: NETSYS45
 VMA INFO: ---------------------------------------------------------------------------
 VMA INFO: Log Level                      INFO                       [VMA_TRACELEVEL]
 VMA INFO: Rx UDP Poll OS Ratio           Disabled                   [VMA_RX_UDP_POLL_OS_RATIO]
 VMA INFO: Select Poll OS Ratio           Disabled                   [VMA_SELECT_POLL_OS_RATIO]
 VMA INFO: ---------------------------------------------------------------------------
 VMA WARNING: ***************************************************************************************
 VMA WARNING: * VMA will not operate properly while flow steering option is disabled                *
 VMA WARNING: * In order to enable flow steering please restart your VMA applications after running *
 VMA WARNING: * the following:                                                                      *
 VMA WARNING: * For your information the following steps will restart your network interface        *
 VMA WARNING: * 1. "echo options mlx4_core log_num_mgm_entry_size=-1 > /etc/modprobe.d/mlnx.conf"   *
 VMA WARNING: * 2. Restart openibd or rdma service depending on your system configuration           *
 VMA WARNING: * Read more about the Flow Steering support in the VMA's User Manual                  *
 VMA WARNING: ***************************************************************************************
 VMA WARNING: *******************************************************************************************************
 VMA WARNING: * Interface p6p1 will not be offloaded.
 VMA WARNING: * Working in this mode might causes VMA malfunction over Ethernet/InfiniBand interfaces
 VMA WARNING: * WARNING: the following steps will restart your network interface!
 VMA WARNING: * 1. "echo options ib_uverbs disable_raw_qp_enforcement=1 > /etc/modprobe.d/ib_uverbs.conf"
 VMA WARNING: * 2. Restart openibd or rdma service depending on your system configuration
 VMA WARNING: * Read the RAW_PACKET QP root access enforcement section in the VMA's User Manual for more information
 VMA WARNING: ******************************************************************************************************
 VMA WARNING: *******************************************************************************************************
 VMA WARNING: * Interface p5p1 will not be offloaded.
 VMA WARNING: * Working in this mode might causes VMA malfunction over Ethernet/InfiniBand interfaces
 VMA WARNING: * WARNING: the following steps will restart your network interface!
 VMA WARNING: * 1. "echo options ib_uverbs disable_raw_qp_enforcement=1 > /etc/modprobe.d/ib_uverbs.conf"
 VMA WARNING: * 2. Restart openibd or rdma service depending on your system configuration
 VMA WARNING: * Read the RAW_PACKET QP root access enforcement section in the VMA's User Manual for more information
 VMA WARNING: ******************************************************************************************************
 VMA WARNING: **************************************************************
 VMA WARNING: * NO IMMEDIATE ACTION NEEDED!
 VMA WARNING: * Not enough hugepage resources for VMA memory allocation.
 VMA WARNING: * VMA will continue working with regular memory allocation.
 VMA INFO:    * Optional:
 VMA INFO:    *   1. Switch to a different memory allocation type
 VMA INFO:    *      (VMA_MEM_ALLOC_TYPE!= 2)
 VMA INFO:    *   2. Restart process after increasing the number of
 VMA INFO:    *      hugepages resources in the system:
 VMA INFO:    *      "echo 1000000000 > /proc/sys/kernel/shmmax"
 VMA INFO:    *      "echo 800 > /proc/sys/vm/nr_hugepages"
 VMA WARNING: * Please refer to the memory allocation section in the VMA's
 VMA WARNING: * User Manual for more information
 VMA WARNING: **************************************************************
sockperf: == version #3.6-no.git ==
sockperf: [SERVER] listen on:
[ 0] IP = 10.1.3.45       PORT = 19140 # TCP
sockperf: Warmup stage (sending a few dummy messages)...
sockperf: [tid 17100] using recvfrom() to block on socket(s)
^Csockperf: Test end (interrupted by user)
sockperf: Total 34294018 messages received and handled
sockperf: cleanupAfterLoop() exit

**Client Side.**

> $ VMA_RX_UDP_POLL_OS_RATIO=0  VMA_SELECT_POLL_OS_RATIO=0 LD_PRELOAD=libvma.so numactl --cpunodebind=0 taskset -c 0,2 sockperf tp --msg-size 64 --ip 10.1.3.45 --port 19140 --tcp --time 600
 VMA INFO: ---------------------------------------------------------------------------
 VMA INFO: VMA_VERSION: 9.0.2-0 Development Snapshot built on Feb 24 2020 20:57:59
 VMA INFO: Git: 1585579238d56e917e650e5381b34a8aaaeca149
 VMA INFO: Cmd Line: numactl --cpunodebind=0 taskset -c 0,2 sockperf tp --msg-size 64 --ip 10.1.3.45 --port 19140 --tcp --time 600
 VMA INFO: Current Time: Mon Mar 23 10:54:59 2020
 VMA INFO: Pid: 24599
 VMA INFO: OFED Version: MLNX_OFED_LINUX-4.7-1.0.0.1:
 VMA INFO: Architecture: x86_64
 VMA INFO: Node: NETSYS46
 VMA INFO: ---------------------------------------------------------------------------
 VMA INFO: Log Level                      INFO                       [VMA_TRACELEVEL]
 VMA INFO: Rx UDP Poll OS Ratio           Disabled                   [VMA_RX_UDP_POLL_OS_RATIO]
 VMA INFO: Select Poll OS Ratio           Disabled                   [VMA_SELECT_POLL_OS_RATIO]
 VMA INFO: ---------------------------------------------------------------------------
 VMA INFO: ---------------------------------------------------------------------------
 VMA INFO: VMA_VERSION: 9.0.2-0 Development Snapshot built on Feb 24 2020 20:57:59
 VMA INFO: Git: 1585579238d56e917e650e5381b34a8aaaeca149
 VMA INFO: Cmd Line: taskset -c 0,2 sockperf tp --msg-size 64 --ip 10.1.3.45 --port 19140 --tcp --time 600
 VMA INFO: Current Time: Mon Mar 23 10:54:59 2020
 VMA INFO: Pid: 24599
 VMA INFO: OFED Version: MLNX_OFED_LINUX-4.7-1.0.0.1:
 VMA INFO: Architecture: x86_64
 VMA INFO: Node: NETSYS46
 VMA INFO: ---------------------------------------------------------------------------
 VMA INFO: Log Level                      INFO                       [VMA_TRACELEVEL]
 VMA INFO: Rx UDP Poll OS Ratio           Disabled                   [VMA_RX_UDP_POLL_OS_RATIO]
 VMA INFO: Select Poll OS Ratio           Disabled                   [VMA_SELECT_POLL_OS_RATIO]
 VMA INFO: ---------------------------------------------------------------------------
 VMA INFO: ---------------------------------------------------------------------------
 VMA INFO: VMA_VERSION: 9.0.2-0 Development Snapshot built on Feb 24 2020 20:57:59
 VMA INFO: Git: 1585579238d56e917e650e5381b34a8aaaeca149
 VMA INFO: Cmd Line: sockperf tp --msg-size 64 --ip 10.1.3.45 --port 19140 --tcp --time 600
 VMA INFO: Current Time: Mon Mar 23 10:54:59 2020
 VMA INFO: Pid: 24599
 VMA INFO: OFED Version: MLNX_OFED_LINUX-4.7-1.0.0.1:
 VMA INFO: Architecture: x86_64
 VMA INFO: Node: NETSYS46
 VMA INFO: ---------------------------------------------------------------------------
 VMA INFO: Log Level                      INFO                       [VMA_TRACELEVEL]
 VMA INFO: Rx UDP Poll OS Ratio           Disabled                   [VMA_RX_UDP_POLL_OS_RATIO]
 VMA INFO: Select Poll OS Ratio           Disabled                   [VMA_SELECT_POLL_OS_RATIO]
 VMA INFO: ---------------------------------------------------------------------------
 VMA WARNING: ***************************************************************************************
 VMA WARNING: * VMA will not operate properly while flow steering option is disabled                *
 VMA WARNING: * In order to enable flow steering please restart your VMA applications after running *
 VMA WARNING: * the following:                                                                      *
 VMA WARNING: * For your information the following steps will restart your network interface        *
 VMA WARNING: * 1. "echo options mlx4_core log_num_mgm_entry_size=-1 > /etc/modprobe.d/mlnx.conf"   *
 VMA WARNING: * 2. Restart openibd or rdma service depending on your system configuration           *
 VMA WARNING: * Read more about the Flow Steering support in the VMA's User Manual                  *
 VMA WARNING: ***************************************************************************************
 VMA WARNING: *******************************************************************************************************
 VMA WARNING: * Interface p5p1 will not be offloaded.
 VMA WARNING: * Working in this mode might causes VMA malfunction over Ethernet/InfiniBand interfaces
 VMA WARNING: * WARNING: the following steps will restart your network interface!
 VMA WARNING: * 1. "echo options ib_uverbs disable_raw_qp_enforcement=1 > /etc/modprobe.d/ib_uverbs.conf"
 VMA WARNING: * 2. Restart openibd or rdma service depending on your system configuration
 VMA WARNING: * Read the RAW_PACKET QP root access enforcement section in the VMA's User Manual for more information
 VMA WARNING: ******************************************************************************************************
 VMA WARNING: *******************************************************************************************************
 VMA WARNING: * Interface p6p1 will not be offloaded.
 VMA WARNING: * Working in this mode might causes VMA malfunction over Ethernet/InfiniBand interfaces
 VMA WARNING: * WARNING: the following steps will restart your network interface!
 VMA WARNING: * 1. "echo options ib_uverbs disable_raw_qp_enforcement=1 > /etc/modprobe.d/ib_uverbs.conf"
 VMA WARNING: * 2. Restart openibd or rdma service depending on your system configuration
 VMA WARNING: * Read the RAW_PACKET QP root access enforcement section in the VMA's User Manual for more information
 VMA WARNING: ******************************************************************************************************
 VMA WARNING: *******************************************************************************************************
 VMA WARNING: * Interface p7p1 will not be offloaded.
 VMA WARNING: * Working in this mode might causes VMA malfunction over Ethernet/InfiniBand interfaces
 VMA WARNING: * WARNING: the following steps will restart your network interface!
 VMA WARNING: * 1. "echo options ib_uverbs disable_raw_qp_enforcement=1 > /etc/modprobe.d/ib_uverbs.conf"
 VMA WARNING: * 2. Restart openibd or rdma service depending on your system configuration
 VMA WARNING: * Read the RAW_PACKET QP root access enforcement section in the VMA's User Manual for more information
 VMA WARNING: ******************************************************************************************************
 VMA WARNING: **************************************************************
 VMA WARNING: * NO IMMEDIATE ACTION NEEDED!
 VMA WARNING: * Not enough hugepage resources for VMA memory allocation.
 VMA WARNING: * VMA will continue working with regular memory allocation.
 VMA INFO:    * Optional:
 VMA INFO:    *   1. Switch to a different memory allocation type
 VMA INFO:    *      (VMA_MEM_ALLOC_TYPE!= 2)
 VMA INFO:    *   2. Restart process after increasing the number of
 VMA INFO:    *      hugepages resources in the system:
 VMA INFO:    *      "echo 1000000000 > /proc/sys/kernel/shmmax"
 VMA INFO:    *      "echo 800 > /proc/sys/vm/nr_hugepages"
 VMA WARNING: * Please refer to the memory allocation section in the VMA's
 VMA WARNING: * User Manual for more information
 VMA WARNING: **************************************************************
sockperf: == version #3.6-no.git ==
sockperf[CLIENT] send on:
[ 0] IP = 10.1.3.45       PORT = 19140 # TCP
sockperf: Warmup stage (sending a few dummy messages)...
sockperf: Starting test...
^Csockperf: Test end (interrupted by user)
sockperf: Test ended
sockperf: Total of 266191784 messages sent in 238.285 sec

sockperf: NOTE: test was performed, using msg-size=64. For getting maximum throughput consider using --msg-size=1472
sockperf: Summary: Message Rate is 1117114 [msg/sec]
**sockperf: Summary: BandWidth is 68.183 MBps (545.466 Mbps)**

2. Linux
**Server Side.**

> $ numactl --cpunodebind=0 taskset -c 0,2 sockperf sr --msg-size 64 --ip 10.1.3.45 --port 19140 --tcp
sockperf: == version #3.6-no.git ==
sockperf: [SERVER] listen on:
[ 0] IP = 10.1.3.45       PORT = 19140 # TCP
sockperf: Warmup stage (sending a few dummy messages)...
sockperf: [tid 17247] using recvfrom() to block on socket(s)
^Csockperf: Test end (interrupted by user)
sockperf: Total 40095122 messages received and handled
sockperf: cleanupAfterLoop() exit

**Client Side.**

> $ numactl --cpunodebind=0 taskset -c 0,2 sockperf tp --msg-size 64 --ip 10.1.3.45 --port 19140 --tcp --time 30
sockperf: == version #3.6-no.git ==
sockperf[CLIENT] send on:
[ 0] IP = 10.1.3.45       PORT = 19140 # TCP
sockperf: Warmup stage (sending a few dummy messages)...
sockperf: Starting test...
sockperf: Test end (interrupted by timer)
sockperf: Test ended
sockperf: Total of 39660366 messages sent in 30.000 sec

sockperf: NOTE: test was performed, using msg-size=64. For getting maximum throughput consider using --msg-size=1472
sockperf: Summary: Message Rate is 1321994 [msg/sec]
**sockperf: Summary: BandWidth is 80.688 MBps (645.505 Mbps)**

**Comment by NirNitzani** [comment]
In order to serve you better please open a case using one of the following methods:
•	Mellanox 24x7 Call Center at +1 408.916.0055; Toll-free (USA only) 86-Mellanox (8663552669) 
•	Open Support case at support@mellanox.com 
•	MyMellanox Customers Portal login 
•	Also available as a Mobile App! 
•	Mellanox Support Live Chat
