### ISSUE TITLE
how use libvma with golang ?

### ISSUE THREAD

**Issue by awzhgw** [Mellanox/libvma#894]
how use libvma with golang ?

**Comment by igor-ivanov** [comment]
Hi @awzhgw,
I think you can do LD_PRELOAD=libvma.so with your go application.

**Comment by mzpqnxow** [comment]
@igor-ivanov golang does not use libc for sockets (or much of anything else, really) so this won't work unfortunately

A completely separate effort will be required to build a libvma interface in golang, which is unfortunate but one of the drawbacks to implementing your own standard library as golang does

You can confirm this with a really simple hook for `socket()` that calls `abort()`:

```
#define _GNU_SOURCE
#include <dlfcn.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/socket.h>

int (*real_socket)(int domain, int type, int protocol) = NULL;

int socket(int domain, int type, int protocol) {
  printf("Hooked socket\n");
  abort();
  return real_socket(domain, type, protocol);
}

__attribute__((constructor)) void load_hooks(void) {
  void *ptr;

  if (!real_socket) {
    ptr = dlsym(RTLD_NEXT, "socket");
    real_socket = ptr;
#ifdef DEBUG
    printf("[*] Wrapping up socket, real @ %p\n", real_socket);
#endif /* DEBUG */
  }
}
```

Build with:

```
$ gcc -fPIC -Wl,-G -Wl,-z,text -shared -ldl -DDEBUG socket.c -o socket.so
```

Confirm `abort()` for standard applications like `telnet`

```
$ LD_PRELOAD=./socket.so telnet www.google.com 443                                                 
[*] Wrapping up socket, real @ 0x7f4b87a16ac0
Hooked socket
[1]    1196 abort      LD_PRELOAD=./socket.so telnet www.google.com 443
```

If you run this with a golang app (that isn't statically linked of course) that uses sockets you'll see the hook get initialized in the constructor, but it won't fire if you perform any socket operations like a TCP connect using golang `Dial()` functions

Would be great if someone built a golang libvma but it's a big effort. Great blueprints but it's essentially completely from scratch

**Comment by ansjsun** [comment]
We have implemented ld preload calls via cgo's epoll. But the multi-threaded performance is not very good.

**Comment by mzpqnxow** [comment]
That's interesting @ansjsun I hadn't thought of that

Is your project publicly available or is a private/proprietary project? I'd be really interested to take a look at it out of curiosity if you can share it

**Comment by mzpqnxow** [comment]
> We have implemented ld preload calls via cgo's epoll. But the multi-threaded performance is not very good.and rust or c server same as。

And actually, if I can add another question for you about how you implemented it- you mention it was a problem with multithreading- were you using goroutines or native OS threads?

**Comment by ansjsun** [comment]
> > We have implemented ld preload calls via cgo's epoll. But the multi-threaded performance is not very good.and rust or c server same as。
> 
> And actually, if I can add another question for you about how you implemented it- you mention it was a problem with multithreading- were you using goroutines or native OS threads?

Sorry this is not open source yet, we are using goroutine. not using native OS threads, but we tested rust std server， and c language epoll server, also single threaded, performance is very good, multi-threaded (50 thread) is very bad。 

it is rust code for server test.

````
mod stdsc;
mod asyncsc;
mod rdma;

fn main() {
	let mut addr = String::from("0.0.0.0:8081");
	let mut cn = 100;
	let mut len = 16384;
	let mut block = String::from("false");
	let mut tp = String::from("client");

	println!("default addr:{} cn:{} len:{} block:{} tp:{}", addr, cn, len, block, tp);
	for arg in std::env::args().skip(1) {
		if arg.is_empty() {
			continue;
		}

		let split: Vec<&str> = arg.split("=").collect();
		if split.len() != 2 {
			panic!(format!("{:#?} has err", split))
		}
		match split[0] {
			"addr" => addr = split[1].to_string(),
			"block" => block = split[1].to_string(),
			"tp" => tp = split[1].to_string(),
			"cn" => cn = split[1].parse().unwrap(),
			"len" => len = split[1].parse().unwrap(),
			_ => panic!("value not in config: {:?}", split)
		}
	}

	println!("real addr:{} cn:{} len:{} block:{} tp:{}", addr, cn, len, block, tp);

	let num = 100000;

	if tp == "server" {
		if block == "true" {
			stdsc::start_server(addr, len, num);
		} else {}
	} else {
		if block == "true" {
			stdsc::start_client(addr, cn, len, num);
		} else {}
	}
}

````

````
use std::net::{TcpListener, TcpStream};
use std::io::{Read, Write};
use std::time::Instant;
use std::thread;
use std::thread::JoinHandle;
use std::ops::Sub;

pub fn start_server(addr: String, len: usize, num: usize) {
	let listener = TcpListener::bind(addr).unwrap();

	loop {
		let (mut conn, _) = listener.accept().unwrap();
		let mut num = num;
		thread::spawn(move || {
			let mut buf = vec![0; len];
			loop {
				match conn.read_exact(&mut buf) {
					Ok(_) => {}
					Err(e) => {
						if num != 0 {
							println!("conn has close......{:?}", e);
						}
						return;
					}
				}
				num -= 1;

				let result = conn.write(&mut buf).unwrap();
				if len != result {
					panic!("length has err: {}/{} ", len, result);
				}
			}
		});
	}
}


pub fn start_client(addr: String, cn: usize, len: usize, num: usize) {
	let now = Instant::now();
	let mut handlers: Vec<JoinHandle<()>> = Vec::new();
	for j in 0..cn {
		let addr = addr.clone();
		let handle = thread::spawn(move || {
			let mut conn = TcpStream::connect(addr).unwrap();
			let now = Instant::now();

			let mut buf = vec![0; len];
			for i in 0..num {
				let result = conn.write(&mut buf).unwrap();
				if len != result {
					panic!("length has err: {}/{} ", len, result);
				}

				conn.read_exact(&mut buf).unwrap();

				if i % 10000 == 0 && j == 0 {
					println!("index:{} client send {:#?}", i, Instant::now().sub(now));
				}
			}
		});

		handlers.push(handle);
	}

	for handler in handlers {
		handler.join().unwrap();
	}

	println!("execute ok use time:{:#?}", Instant::now().sub(now));
}
````

**Comment by mzpqnxow** [comment]
Thanks for sharing @ansjsun!

@awzhgw do you plan to keep this issue open? I'm not sure there's an easy answer aside from what @ansjsun mentioned- using cgo to link in libc and then using libvma. It's a bit of work I think, probably more than can be covered in this issue. I think it's safe to say there is no official support from libvma maintainers for using libvma with golang, unfortunately. I can understand why, and you can thank golang design choices for that :)

**Comment by igor-ivanov** [comment]
@mzpqnxow, @awzhgw, @ansjsun thank you for sharing this information. As @awzhgw mentioned libvma does not support golang.
