### ISSUE TITLE
The following VMA_ERRORs will be displayed when running ping with root permissions or with no-root user

### ISSUE THREAD

**Issue by littleyanglovegithub** [Mellanox/libvma#910]
Hello, the error follows: 
[kuanrui@localhost ~]$ LD_PRELOAD=libvma.so ping 10.6.22.41
 VMA INFO: ---------------------------------------------------------------------------
 VMA INFO: VMA_VERSION: 9.0.2-0 Release built on Apr  1 2020 13:54:44
 VMA INFO: Cmd Line: ping 10.6.22.41
 VMA INFO: OFED Version: MLNX_OFED_LINUX-5.0-2.1.8.0:
 VMA INFO: ---------------------------------------------------------------------------
 VMA INFO: Log Level                      INFO                       [VMA_TRACELEVEL]
 VMA INFO: ---------------------------------------------------------------------------
 VMA ERROR: ring_simple[0x7f43d8d47f60]:242:create_resources() ibv_create_comp_channel for tx failed. m_p_tx_comp_event_channel = (nil) (errno=13 Permission denied)
PING 10.6.22.41 (10.6.22.41) 56(84) bytes of data.
64 bytes from 10.6.22.41: icmp_seq=1 ttl=63 time=0.042 ms
64 bytes from 10.6.22.41: icmp_seq=2 ttl=63 time=0.021 ms
64 bytes from 10.6.22.41: icmp_seq=3 ttl=63 time=0.020 ms
64 bytes from 10.6.22.41: icmp_seq=4 ttl=63 time=0.019 ms
^C
--- 10.6.22.41 ping statistics ---
4 packets transmitted, 4 received, 0% packet loss, time 3002ms
rtt min/avg/max/mdev = 0.019/0.025/0.042/0.010 ms

**Comment by igor-ivanov** [comment]
I can not reproduce this issue on ofed 4.9-2.1.4.0 and 5.1-2.3.2.0
