### ISSUE TITLE
Link to vma homepage is broken

### ISSUE THREAD

**Issue by bmerry** [Mellanox/libvma#912]
The README.md has a link to http://www.mellanox.com/vma/, which doesn't exist.

**Comment by igor-ivanov** [comment]
Thank you @bmerry for pointing to the issue. We will solve

**Comment by igor-ivanov** [comment]
https://github.com/Mellanox/libvma/pull/916

**Comment by igor-ivanov** [comment]
https://github.com/Mellanox/libvma/commit/a072dd051e6e5717d8d5259b765308112f4a958f
