### ISSUE TITLE
Support for "ConnectX-6" and "Connectx-6 dx" cards

### ISSUE THREAD

**Issue by Donis-** [Mellanox/libvma#938]
Latest 
"NVIDIA MELLANOX Messaging Accelerator (VMA) Documentation Rev 9.2.2" 
https://docs.mellanox.com/spaces/viewspace.action?key=VMAv922
states:
System Requirements, Network Adapter Cards:
ConnectX®-4/ConnectX®-4 Lx
ConnectX®-5/ConnectX®-5 Ex

Then it also has:
On-Device Memory is supported in ConnectX-5 adapter cards and above.

But the full VMA feature support state for ConnectX-6 and Connectx-6 dx is unclear. 
Is VMA supported on ConnectX-6 and Connectx-6 dx network adapters?

**Comment by NirNitzani** [comment]
Hi @Donis- 

For best latency performance we are recommending to use VMA with ConnectX-5.
It will be helpful to know which use case you are targeting with VMA and ConnectX-6.

Thanks

**Comment by Donis-** [comment]
Hi @NirNitzani,

Thanks. We went with  MT28800 Family [ConnectX-5 Ex] to be sure we can use VMA.
Our use case is low latency TCP reception & transmission in the financial industry.
