### ISSUE TITLE
Why multi-threaded performance gets worse.

### ISSUE THREAD

**Issue by ansjsun** [Mellanox/libvma#945]
Why multi-threaded performance gets worse.
I use tcp+epoll model. Single threaded is 1X better than standard library. But with multi-threaded 50 clients doing echo at the same time. The speed is twice slower than the standard library. Is there some parameter not set correctly? I tried some but it didn't work.

**Comment by awzhgw** [comment]
the client role cpu has full ???

**Comment by igor-ivanov** [comment]
Hello @ansjsun, There is no single recommendation to tune target application. You can look to `VMA_RING_ALLOCATION_LOGIC_TX`, `VMA_RING_ALLOCATION_LOGIC_RX` parameters.  But small number of threads is preferable scenario to get better profit.

**Comment by ansjsun** [comment]
@igor-ivanov thx i will try it
