### ISSUE TITLE
Unable to see vma stats file on server side

### ISSUE THREAD

**Issue by ps142020** [Mellanox/libvma#949]
I am trying libvma with grpc, with client sending a ping and server responds with pong. I see latency reduces from 85us to 55us with libvma on both client and server side. I can see vma stats on client side however not seeing vma stats on server side. Any thoughts?

**Comment by ps142020** [comment]
Any updates? I also see "Operation in progress" message in client side vma logs, still vma stats file show offloaded packets count. Is something missing here?

**Comment by ps142020** [comment]
On client side these are the stats I see, should TX and Rx match up?
======================================================
        Fd=[23]
- UDP, Blocked, MC Loop Enabled
- Local Address   = [192.168.140.199:46133]
- Foreign Address = [192.168.140.100:50051]
Rx and Tx where not active
======================================================
        Fd=[23]
- TCP, Non-blocked
- Local Address   = [192.168.140.199:34771]
- Foreign Address = [192.168.140.100:50051]
Tx Offload: 108400 / 1000041 / 0 / 0 [kilobytes/packets/eagains/errors]
Rx Offload: 65431 / 1257784 / 1996181 / 0 [kilobytes/packets/eagains/errors]
Rx byte: cur 0 / max 171 / dropped 0 / limit 0
Rx pkt : cur 0 / max 1 / dropped 0
======================================================
~

**Comment by igor-ivanov** [comment]
`vma_stats` shows statistic from any process using TCP/UDP sockets. You can find more details using User Manual pages https://docs.mellanox.com/display/VMAv922/Monitoring%2C+Debugging%2C+and+Troubleshooting
