### ISSUE TITLE
Who creates NETLINK_RDMA socket

### ISSUE THREAD

**Issue by ps142020** [Mellanox/libvma#951]
I am using strace to dump out all the sys calls and see that while using libvma with LD_PRELOAD, a socket is created with NETLINK_RDMA, but cant find this being done in either libvma or libnl source code. where is this socket creation happening?

socket(AF_NETLINK, SOCK_RAW|SOCK_CLOEXEC, NETLINK_RDMA)

**Comment by igor-ivanov** [comment]
VMA supports offloading with profit of `SOCK_DGRAM` and `SOCK_STREAM` socket protocols.
