### ISSUE TITLE
Can't access local server 

### ISSUE THREAD

**Issue by liguochao** [Mellanox/libvma#955]
Why processes using libvma.so cannot access local standard TCP services?
The vma version is v9.3.1 and log is here[ [vma.log](https://github.com/Mellanox/libvma/files/6653254/vma.log) ]
My machine local IP is 10.65.36.75, and the local standard TCP service using port 17896, but cant see anything by 'vma_stats -v 5'
![image](https://user-images.githubusercontent.com/7479008/122003249-6cb5f100-cde5-11eb-9cdc-7a7aabbd9a06.png)

Information from 'netstat -anpl':
![image](https://user-images.githubusercontent.com/7479008/122003927-4e042a00-cde6-11eb-9cb2-0aaa5164e676.png)

**Comment by igor-ivanov** [comment]
I guess that in your sceanrio one side is under VMA and the other side is under OS. It is know VMA limitation. Ethernet loopback is not functional between the VMA and the OS

**Comment by liguochao** [comment]
So, tcp should be auto used when access local service.

**Comment by igor-ivanov** [comment]
What do you mean?
You can use VMA<->VMA on the same node but can not do VMA<->OS
