### ISSUE TITLE
Add application-id match rule but does not work

### ISSUE THREAD

**Issue by liguochao** [Mellanox/libvma#956]
Add application-id match rule but does not work, because the default 'application-id * *' rule in the configuration file is matched first.
I think, the 'application-id * *' rule should be the lowest priority, and the rules of application-id should be matched according to the priority of accuracy(such as route selection in linux kernel).

**Comment by igor-ivanov** [comment]
Hello @liguochao,
You can study VMA used logic at https://github.com/Mellanox/libvma/blob/1369a2bedb27026d961912c32aaaa6a1e9d5a3eb/src/vma/util/match.cpp#L427
