### ISSUE TITLE
Shared resource among vma clients

### ISSUE THREAD

**Issue by ps142020** [Mellanox/libvma#958]
I am running an application with 12 of them launched on 12 different cores vs 1 core. I expected when all 12 process run on single core latency should increase due to obvious but turns out vma performs much better than 12 cores case. What is the shared resource here? i am not even running vma. Also from mlx_fs_dump i always see 12 queues. Is there any info on details of vma architecture?

**Comment by ps142020** [comment]
Any update on this?

**Comment by igor-ivanov** [comment]
Hello @ps142020. You can find information about VMA using wiki: https://github.com/Mellanox/libvma/wiki or User Manual: https://docs.mellanox.com/spaces/viewspace.action?key=VMAv922
