### ISSUE TITLE
socket() fails with memory allocation error after exec()

### ISSUE THREAD

**Issue by andrej** [Mellanox/libvma#959]
Opening a socket, then replacing the running process with exec(), and then trying to open _another_ socket in the parent process results in the following error:

    VMA ERROR: ibch272:mem_reg() failed registering a memory region (errno=12 Cannot allocate memory)
    VMA WARNING: allocator[0x1570ab0]:305:register_memory() Failure during memory registration on dev: mlx5_0 addr=(nil) length=62400063
    VMA WARNING: allocator[0x1570ab0]:343:register_memory() Failed registering memory, This might happen due to low MTT entries. Please refer to README.txt for more info

The following is a minimal example to reproduce the bug:

    #include <cstdio>
    #include <unistd.h>
    #include <sys/socket.h>
    
    int main(int argc, char **argv)
    {
    	int sock;
    	if((sock = socket(AF_INET, SOCK_STREAM, 0)) < 0) { perror("socket"); }
    
    	if(argc > 1) {
    		char *args[] = {argv[0], NULL};
    		if(execvp(args[0], args) == -1) { perror("execvp"); }
    	}
    	return 0;
    }

To reproduce the error, compile attached code, and run it as such:

    $ g++ -o vmatest2 vmatest2.cpp
    $ LD_PRELOAD="/usr/lib/libvma.so" ./vmatest2 arg

This is on Ubuntu 16.04.7 LTS (GNU/Linux 4.15.0-142-generic x86_64) with VMA_VERSION: 8.7.0-0 Development Snapshot built on Aug  9 2018 10:06:59.

[vma-bug.zip](https://github.com/Mellanox/libvma/files/6792864/vma-bug.zip)

**Comment by igor-ivanov** [comment]
Hello @andrej,

Try to set `VMA_MEM_ALLOC_TYPE=2` or `VMA_MEM_ALLOC_TYPE=0`.

For example:
```
$ sudo VMA_MEM_ALLOC_TYPE=2 LD_PRELOAD=libvma.so ./a.out arg
```
