### ISSUE TITLE
Problems encountered while  running './configure...'

### ISSUE THREAD

**Issue by yushilingco** [Mellanox/libvma#968]
$ ./configure --with-ofed=/usr --prefix=/usr --libdir=/usr/lib64 --includedir=/usr/include --docdir=/usr/share/doc/libvma --sysconfdir=/etc

...
configure: error: Unable to find the librdmacm-devel header files

Then I try to install:
sudo apt-get install librdmacm1
So I get it:
librdmacm1 is already the newest version (17.1-1ubuntu0.2).

But I still failed after installation.I hereby ask for the reason. Thank you very much.

**Comment by igor-ivanov** [comment]
Hi @yushilingco 
could you please install `librdmacm-dev` as requested in error message.

**Comment by igor-ivanov** [comment]
@yushilingco you can reopen in case https://github.com/Mellanox/libvma/issues/968#issuecomment-956458365 doe snot help
