### ISSUE TITLE
clarify the usage of vma daemon (vmad)

### ISSUE THREAD

**Issue by andl** [Mellanox/libvma#975]
## Issue type
- [] Bug report
- [x] Feature request

## Configuration:
* Product version vma 8.7.5
* OS Centos 7.6
* OFED 4.5-1.0.1.0
* Hardware connectx-5

## Actual behavior:
Hi,
I found following debug log when I tried vma + redis-cli on centos 7.6, the log indicates vmad is not running. Unfortunately, I didn't find useful document for it after searching docs site and github. All I got is this link but only for windows platform https://docs.mellanox.com/display/VMAv875/Debugging%2C+Troubleshooting%2C+and+Monitoring. My question is whether vmad is necessary on linux platform? If yes, can I get detailed document of how to configure this daemon.   
```
Pid: 89863 Tid: 89863 VMA DEBUG: *************************************************************
Pid: 89863 Tid: 89863 VMA DEBUG: * Can not establish connection with the daemon (vmad).      *
Pid: 89863 Tid: 89863 VMA DEBUG: * UDP/TCP connections are likely to be limited.             *
Pid: 89863 Tid: 89863 VMA DEBUG: *************************************************************
```

**Comment by igor-ivanov** [comment]
VMA daemon is needed for Azure and cleanup procedure in case unexpected termination.

**Comment by andl** [comment]
> VMA daemon is needed for Azure and cleanup procedure in case unexpected termination.

Hi igor, since i'm not using Azure, I guess I can safely ignore this warning right?

**Comment by igor-ivanov** [comment]
It does not impact functionality but allows to do correct cleanup in some cases.

**Comment by andl** [comment]
thanks, I'll close this issue.
