### ISSUE TITLE
How to estimate a number of huge pages required by libvma?

### ISSUE THREAD

**Issue by isliser** [Mellanox/libvma#978]
I'm going to start using libvma with huge pages enabled but it's not clear how to estimate memory requirements. Is there any described method or I should use empiric data? 
Any suggestions are welcome!

**Comment by igor-ivanov** [comment]
Hello @isliser
Huge pages are used for internal rx /tx buffers mostly.
So you can estimate required memory as `VMA_RX_BUFS * BUF_SIZE(MTU) + VMA_TX_BUFS * BUF_SIZE(MTU)`

**Comment by isliser** [comment]
@igor-ivanov Спасибо!
