### ISSUE TITLE
libvma time  is not monotonically increasing

### ISSUE THREAD

**Issue by datar** [Mellanox/libvma#98]
Hi everybody,

I used libvma with sockperf to do latency test.
I save libvma log file with TRACELEVEL=FINE.

It looks like the time column is not monotonically increasing.
These lines is a cycle from sockperf client tx() to next tx().
The 2nd line's time is late than next tx().
What does it mean?
Does libvma use different clocks?

```
Time:  3318.920 Pid:  7075 Tid:  7075 VMA FINE: si_udp[fd=20]:1524:tx() 
Time:  3318.975 Pid:  7075 Tid:  7075 VMA FINE: qpm[0x202b830]:481:send() 
Time:  3318.925 Pid:  7075 Tid:  7075 VMA FINE: si_udp[fd=20]:1180:rx() 
Time:  3318.872 Pid:  7075 Tid:  7075 VMA FINE: ring_simple[0x20135b0]:719:rx_process_buffer() Rx ip packet info: dst=192.168.1.2, src=192.168.1.1, packet_sz=92, offset=0, id=0, proto=UDP[17] (local if: 192.168.1.2)
Time:  3318.875 Pid:  7075 Tid:  7075 VMA FINE: ring_simple[0x20135b0]:792:rx_process_buffer() Rx udp datagram info: src_port=23228, dst_port=50779, payload_sz=64, csum=0x8d9b
Time:  3318.881 Pid:  7075 Tid:  7075 VMA FINE: wakeup_pipe[epfd=22]:69:do_wakeup() There is no thread in epoll_wait, therefore not calling for wakeup
Time:  3318.950 Pid:  7075 Tid:  7075 VMA FINE: si_udp[fd=20]:1814:rx_input_cb() rx ready count = 1 packets / 64 bytes
Time:  3318.952 Pid:  7075 Tid:  7075 VMA FINE: si_udp[fd=20]:1468:is_readable() => polled true (ready count = 1 packets / 64 bytes)
Time:  3318.955 Pid:  7075 Tid:  7075 VMA FINE: si_udp[fd=20]:1299:rx() returning with: 64
Time:  3318.957 Pid:  7075 Tid:  7075 VMA FINE: si_udp[fd=20]:1524:tx() 
```

Thank you very much!

**Comment by rosenbaumalex** [comment]
Yes, I see what you mean..  and it is on the same thread: `Tid: 7075`
Does the thread have affinity to a single CPU core?
Maybe it is moving between CPU's.

This logger clock comes from [`vlog_get_usec_since_start()`](https://github.com/mellanox/libvma/blob/master/src/vlogger/vlogger.h#L190), which is based on VMA's rdtsc from [`gettime(struct timespec *ts)`](https://github.com/mellanox/libvma/blob/master/src/vma/util/rdtsc.h#L111).

We need to check that the logic we use to convert TCS into `struct timespec` is correct.

**Comment by datar** [comment]
Thank you, @rosenbaumalex .

It seems like time stamps come from three clocks.

clock 1
```
Time:  3318.920 Pid:  7075 Tid:  7075 VMA FINE: si_udp[fd=20]:1524:tx() 
Time:  3318.925 Pid:  7075 Tid:  7075 VMA FINE: si_udp[fd=20]:1180:rx() 
Time:  3318.950 Pid:  7075 Tid:  7075 VMA FINE: si_udp[fd=20]:1814:rx_input_cb() rx ready count = 1 packets / 64 bytes
Time:  3318.952 Pid:  7075 Tid:  7075 VMA FINE: si_udp[fd=20]:1468:is_readable() => polled true (ready count = 1 packets / 64 bytes)
Time:  3318.955 Pid:  7075 Tid:  7075 VMA FINE: si_udp[fd=20]:1299:rx() returning with: 64
Time:  3318.957 Pid:  7075 Tid:  7075 VMA FINE: si_udp[fd=20]:1524:tx() 
```

clock 2
```
Time:  3318.872 Pid:  7075 Tid:  7075 VMA FINE: ring_simple[0x20135b0]:719:rx_process_buffer() Rx ip packet info: dst=192.168.1.2, src=192.168.1.1, packet_sz=92, offset=0, id=0, proto=UDP[17] (local if: 192.168.1.2)
Time:  3318.875 Pid:  7075 Tid:  7075 VMA FINE: ring_simple[0x20135b0]:792:rx_process_buffer() Rx udp datagram info: src_port=23228, dst_port=50779, payload_sz=64, csum=0x8d9b
Time:  3318.881 Pid:  7075 Tid:  7075 VMA FINE: wakeup_pipe[epfd=22]:69:do_wakeup() There is no thread in epoll_wait, therefore not calling for wakeup
```
clock 3
```
Time:  3318.975 Pid:  7075 Tid:  7075 VMA FINE: qpm[0x202b830]:481:send() 
```


I used options `--sender-affinity`  `--receiver-affinity` in sockperf client.
sender thread and receiver thread ran on different cores.
Does vma run on other cores? If so, how to affinity threads from vma?

**Comment by rosenbaumalex** [comment]
Hi @datar,
Commit https://github.com/Mellanox/libvma/commit/d0714a584749e72d655644ff8bef09c31bef8198 tries to fix/improve the clock stamping issue. Can you give it a try?
PS: on some machines I still see the clock jump. I'm still investigating it.

What CPU are you using? 
Can you paste here the `$ lscpu` output? 
(or more detailed as `$ cat /proc/cpuinfo | tail -n 26`)

**Comment by datar** [comment]
Thank you @rosenbaumalex ,
I'll try the new commit.
Here is the output from `$ cat /proc/cpuinfo | tail -n 26`

> processor	: 19
vendor_id	: GenuineIntel
cpu family	: 6
model		: 79
model name	: Intel(R) Xeon(R) CPU E5-2689 v4 @ 3.10GHz
stepping	: 1
microcode	: 0xb000010
cpu MHz		: 1199.917
cache size	: 25600 KB
physical id	: 1
siblings	: 10
core id		: 12
cpu cores	: 10
apicid		: 56
initial apicid	: 56
fpu		: yes
fpu_exception	: yes
cpuid level	: 20
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch ida arat epb pln pts dtherm tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm rdseed adx smap xsaveopt cqm_llc cqm_occup_llc
bogomips	: 6358.34
clflush size	: 64
cache_alignment	: 64
address sizes	: 46 bits physical, 48 bits virtual
power management:

**Comment by olgk** [comment]
Hi @datar,
was the issue you saw solved by mentioned commit?

Thanks,
Oleg.

**Comment by datar** [comment]
Hi @olgk ,
Sorry for late reply. I'm working on it.
Please close this issue.
Thank you.

**Comment by ilansmith** [comment]
Closing.
This issue was handled in https://github.com/Mellanox/libvma/commit/d0714a584749e72d655644ff8bef09c31bef8198.
