### ISSUE TITLE
Unable to find the libibverbs-devel header files

### ISSUE THREAD

**Issue by yoyopdc** [Mellanox/libvma#980]
## Subject
run     command :
./configure --with-ofed --enable-tcp-tx-wnd-availability --enable-tso

did not success

configure: error: Unable to find the libibverbs-devel header files

but  libibverbs-devel  is installed

the output is :

checking for gcov support... no
checking for time measurement support... no
checking for valgrind support... no
checking for OFED path... yes
checking infiniband/verbs.h usability... no
checking infiniband/verbs.h presence... yes
configure: WARNING: infiniband/verbs.h: present but cannot be compiled
configure: WARNING: infiniband/verbs.h:     check for missing prerequisite headers?
configure: WARNING: infiniband/verbs.h: see the Autoconf documentation
configure: WARNING: infiniband/verbs.h:     section "Present But Cannot Be Compiled"
configure: WARNING: infiniband/verbs.h: proceeding with the compiler's result
configure: WARNING:     ## ----------------------------------- ##
configure: WARNING:     ## Report this to support@mellanox.com ##
configure: WARNING:     ## ----------------------------------- ##
checking for infiniband/verbs.h... no
configure: error: Unable to find the libibverbs-devel header files
## Issue type
- [ x] Bug report
- [ ] Feature request

## Configuration:
* libvma-9.4.0
* centos7
* OFED 5.0-2.1.8.0
* mlx5

## Actual behavior:
./configure --with-ofed --enable-tcp-tx-wnd-availability --enable-tso
## Expected behavior:
configure success

**Comment by igor-ivanov** [comment]
`--with-ofed` can be used when ofed is installed in not standard location.
In case ofed is under /usr folder `--with-ofed` can be omitted or set `--with-ofed=/usr`

**Comment by yoyopdc** [comment]
Hi igor-ivanov:
     this solution is sucesss.
thanks
