### ISSUE TITLE
VMA support with Connectx-6 VPI HCAs

### ISSUE THREAD

**Issue by jmb64** [Mellanox/libvma#985]
## VMA support with Connectx-6 VPI HCAs
  
     The question has been asked before (issue #938)  but the response was not clear
 (ConnectX-5 or 4 was suggested as a better option).
Is it possible for a client-server application communicating through TCP sockets
to benefit (in terms of throughput)  from the VMA library on a RHEL8.3 (Ootpa) cluster 
interconnected through an infiniband network and Mellanox(Nvidia) ConnectX-6 VPI HCAs ?
The documentation (https://github.com/Mellanox/libvma/wiki/A---VMA-Basic-Usage)
appears to be silent even on the subject of the availability of this bypass library.

Nodes are powered by 2 Intel Ice Lake processors (40 cores each).  

rpm -qa | grep -E "rdma|infiniband|uverbs|ucx|vma" | grep -v "kernel-kernel"

infiniband-diags-54mlnx1-1.54103.x86_64
ucx-devel-1.11.0-1.54103.x86_64
ucx-ib-1.11.0-1.54103.x86_64
librdmacm-54mlnx1-1.54103.x86_64
librdmacm-utils-54mlnx1-1.54103.x86_64
ucx-cma-1.11.0-1.54103.x86_64
rdma-core-devel-54mlnx1-1.54103.x86_64
ucx-rdmacm-1.11.0-1.54103.x86_64
rdma-core-54mlnx1-1.54103.x86_64
ucx-knem-1.11.0-1.54103.x86_64
ucx-1.11.0-1.54103.x86_64

(No libvma currently installed ...)

Thanks for any information on the subject.

Jean-Marc

**Comment by igor-ivanov** [comment]
VMA describes CX5 as supported at https://docs.nvidia.com/networking/display/VMAv940/System+Requirements+and+Interoperability
There is another solution as XLIO including CX6 in list of supported devices. See https://docs.nvidia.com/networking/display/xliov118/System+Requirements+and+Interoperability

**Comment by jmb64** [comment]
Hi,

   I've been told on Nvidia Developer's Forum this:

"...VMA will support both Ethernet and InfiniBand Technologies, and that includes the ConnectX-6 VPI adapter as well ..."

A quick look at XLIO doc. tells me that this is for Ethernet network only ...

I guess VMA will have to be installed and tested to really find out !

Thanks,

JM

**Comment by igor-ivanov** [comment]
In case you are interested in IPoIB look following limitations as https://docs.nvidia.com/networking/display/VMAv940/Changes+and+New+Features#ChangesandNewFeatures-DeprecatedFeaturesandSupport (`IPoIB is temporarily unavailable when working with MLNX_OFED v5.1`)
